### ISSUE TITLE
CreateFile() nginx.pid failed

### ISSUE THREAD

**Issue by marxo** [WPN-XM/WPN-XM#116]
I did a fresh install of WPИ-XM and after trying to see phpinfo() I get the 404 error in my browser. The same error stands for anything else that should be visible.

The nginx error shows this:

    2013/08/03 17:00:10 [error] 1084#1932: CreateFile() "C:\server\bin\nginx/logs/nginx.pid" failed (2: The system cannot find the file specified)

**Comment by klonos** [comment]
I still see this error with SCP 0.8.0

**Comment by klonos** [comment]
Thanx for reopening the issue. Let me know if there's anything I can do.

**Comment by jakoch** [comment]
I finally found out how to reproduce this log entry using WPN-XM v0.8.1.
It' simply the Stop Button of Nginx, that means that the stop command used must be wrong.

https://github.com/WPN-XM/server-control-panel/blob/master/src/servers.cpp#L259

If Nginx is already down, then there is no PID file - the error message of Nginx might simply be wrong.
The goal would be to figure out, how to stop this error from filling the log.

**Comment by jakoch** [comment]
It's Nginx. Should be reported over at their tracker.

```
C:\server-081-std-56-w32>bin\nginx\nginx -s stop -c bin\nginx\conf\nginx.conf
nginx: [error] CreateFile() "C:\server-081-std-56-w32/logs/nginx.pid" failed (2: FormatMessage() error:(15100))
```
