### ISSUE TITLE
add port already in use check to SCP

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#155]
- [ ] add a check for ports, which are already in use to the method `MainWindow::checkAlreadyActiveDaemons()`
- [ ] maybe parse output of `netstat -abno` to get name of executable by port
  - not possible without elevated rights
##

**Comment by jakoch** [comment]
- GetTcpTable
- GetOwnerModuleFromTcpEntry

**Comment by jakoch** [comment]
![used-ports-check](https://cloud.githubusercontent.com/assets/85608/24109116/fc35dc20-0d8f-11e7-940d-083ecd3aa95d.png)

Well, the list of ports is now displayed, but it's not that useful, i guess.
I could possibly filter the system ports out - or only list 80,8080,443 and other common ports.

I'm not sure how to improve this. Feedback welcome.

**Comment by jakoch** [comment]
- 80, 8080 and 443 are now highlighted
- chrome.exe is filtered out

![used-ports-filtered-highlight](https://cloud.githubusercontent.com/assets/85608/24110284/5a6c5ca8-0d93-11e7-9378-224183ea05d5.png)

**Comment by jakoch** [comment]
![used-ports-filtered-highlight2](https://cloud.githubusercontent.com/assets/85608/24112127/ce10e336-0d98-11e7-8b72-b0d786a9feff.png)

**Comment by klonos** [comment]
Yes, I would suggest filtering things out too. Not sure if you are filtering by process name or by process path, but I think the latter is safest (in case some users have "rogue" apps installed; say left-overs from trying other stacks). You should already have a way to get the installation path (IIRC you are adding that to the system PATH variable). All you'd then have to do is compare it to the processes paths.

That modal might get quite long. Are you switching to scrollbars after a certain amount of processes? I think you should either be doing that, or better yet, completely filter out all non-WPN-XM processes and hide them in a "show all processes" button/checkbox. I believe that showing all that info is out of the application scope though. You should only show the ports that should be reserved for the stack components.

The red/green text was a really nice touch 👍
