### ISSUE TITLE
Web Control Panel Start/Stop services

### ISSUE THREAD

**Issue by luesak** [WPN-XM/WPN-XM#303]
Hi,

Here's an idea to make the start/stop services more robust on the web cp. 
If you see on a wireless router... when you make config changes... there is not "STOP" and "START" commands.. only "Reboot" or "Restart".

Since the web cp relies on both Nginx and PHP... these two components should only offer a restart button on the web CP.

On Restart... the web will show a count down timer e.g. 10 seconds. Upon the completion of the 10 seconds, it will javascript refresh itself on to the same url. This is the typical behavior for wireless routers.

What do you think?

Kim

**Comment by jakoch** [comment]
The start& stop buttons are only shown if not running via nginx.
The start stop buttons are available when running via PHP embedded webserver.
The restart is now ajax based and contains a delayed check, if the server is up again.
The status indicator of the server is changed accordingly.
Tooltip were added to the buttons.
