### ISSUE TITLE
imagemagick link is down

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#312]
the zip release is not accessible anymore.  **why is nobody reporting this?**
http://www.imagemagick.org/download/binaries/ImageMagick-6.9.0-4-Q16-x86-windows.zip

- [ ] crawler
 - new URL is where?
- [ ] installers
   - change from "zip" to "7z" 
- [ ] registry
- [ ] adjust downloadFilenames (zip to 7z)

**Comment by klonos** [comment]
> **why is nobody reporting this?**

Haven't reinstalled in ages.

**Comment by jakoch** [comment]
No problem.

I've contacted the ImageMagick developers to find out where the download is gone or what the new URL is.

**Comment by jakoch** [comment]
I got no answer to my mail - but they rebuild 6.9.0.4. 
So, the file is up again.
