### ISSUE TITLE
build server-control-panel for windows on linux

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#316]
- [x] .travis.yml
- [x] Install via `wine` or `winelib` or cross-compile with `mingw`?
  - [ ] wine
  - [x] mingw
  - additional Windows dependencies for Qt
   - http://qt-project.org/wiki/MinGW-64-bit
   - http://sourceforge.net/projects/mingwbuilds/
- [x] `qmake` or switch to `cmake`?
    - [x] qmake
    - [ ] cmake
- [x] compile
 - [x] windows.h not found. 

        ```
        In file included from src/main.cpp:30:0:
        src/cli.h:5:21: fatal error: windows.h: No such file or directory
        compilation terminated.
        ```
     
 - solved:

       
          - if [ $BITSIZE == 32 ]; then sudo apt-get install -y mingw32-x-binutils mingw32-x-gcc mingw32-x-runtime; fi
          - if [ $BITSIZE == 64 ]; then sudo apt-get install -y mingw64-x-binutils mingw64-x-gcc mingw64-x-runtime; fi

- [x] test executable with wine

**Comment by jakoch** [comment]
http://stackoverflow.com/questions/28155308/how-to-cross-compile-with-mingw-on-linux-for-windows

**Comment by jakoch** [comment]
Bounty: 500 Euro.

**Comment by jakoch** [comment]
The Server Control Panel is now build with mingw on Travis-CI for Windows x32 and x64.
The image shows a test run of the executable (`wpn-xm.exe --help`) executed with `wine` on Travis.
The deployment from Travis to Github Releases is the last step in order to get continuous builds working.

![exec-test-for-thewindows-scp-on-travis-via-wine](https://cloud.githubusercontent.com/assets/85608/6341385/0e0005da-bbca-11e4-8a93-161b88b498b1.gif)

**Comment by jakoch** [comment]
@klonos Hey Gregory, would you be so nice to test the upcoming release of the SCP?
You find it over here: https://github.com/WPN-XM/server-control-panel/releases/tag/0.8.1-alpha
We need to make sure, that the zip includes all Qt dependencies to start the application.

**Comment by jakoch** [comment]
Ok, nevermind - i used Dependency Walker for checking.

- IESHIMS.DLL is missing

    According to StackOverflow (http://stackoverflow.com/a/2465488/1163786)
    ieshims.dll is an artefact of Vista/7 where a shim DLL is used to proxy certain calls (such as CreateProcess) to handle protected mode IE, which doesn't exist on XP, so it is unnecessary. 

- the x32 packages contains x64 dlls
- the x64 package is ok

**Comment by klonos** [comment]
@jakoch Sorry Jens, been working 16h a day + 2h travel back and forth, so was not active in GitHub (or any other place) for the past 2 weeks. I'm about to test the 0.8.1 release and will report any issues.
