### ISSUE TITLE
Easier way to toggle local/remote access for nginx.

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#319]
I develop locally on my laptop and I often test on various mobile devices. This is what I do currently:

1. Edit nginx config...
2. comment ```listen 127.0.0.1:80;``` out,
3. remove the ```#``` in front of the ```listen 80;``` a few lines below.
4. Start SCP and restart nginx

Once the testing is done, I revert the changes made to ```nginx.conf``` (security reasons) and restart nginx.

I'm sure there must be others in the same situation as myself. Can there be a way to automate this a bit? Does nginx support loading custom .conf files? If so, we could add a toggle in the SCP (preferably in the nginx submenu). Something like a "Listen to local" / "Listen to remote" that restarts nginx with the appropriate .conf file.

**Comment by jakoch** [comment]
Yes, the commented out section (# listen 80) in nginx.conf is the default "catch-all" configuration.
This section was added to the config, because the question for access from outside popped up before.

I like the idea of automating this with a toggle in the webinterface.
:+1:

**Comment by jakoch** [comment]
I'm looking for a good name for the checkbox regarding this feature.
- [ ] Protect server from external access
- [ ] Allow access from localhost only
- [ ] ...

Which one is more clear? Any ideas or suggestions?

**Comment by klonos** [comment]
I think a radio button set with two options would be best:

[ ] allow only local access
[ ] allow access from any computer

**Comment by jakoch** [comment]
What happens if someone enables both checkboxes?

**Comment by klonos** [comment]
> What happens if someone enables both checkboxes?

That's why in my comment I said "radio button set" - not checkboxes. With [radio buttons](https://en.wikipedia.org/wiki/Radio_button) you can only choose one of the available options.

**Comment by jakoch** [comment]
Thank you for clarifying this. I will follow your suggestion.

**Comment by klonos** [comment]
Thank you for considering this feature and for your time.spent in implementing it. I really appreciate it.

**Comment by jakoch** [comment]
Implemented.
