### ISSUE TITLE
Nginx Virtual Host - always redirected to webinterface

### ISSUE THREAD

**Issue by Racochejl** [WPN-XM/WPN-XM#324]
I've defined virtual host in `domains-enabled/` like so

    # content of project.conf
    server {
        listen       	127.0.0.1:80;
        server_name		.localproject.net;
        root		    www/project/dist;
        index		    index.php;
    
        location ~ \.php$ {
                try_files      $uri =404;
                fastcgi_pass   127.0.0.1:9100;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                include        fastcgi_params;
            }
    }

and added reference to my `hosts` file.

    # content of hosts
    127.0.0.1	localproject.net

When I access `http://localproject.net` it *always* opens WPN-XM redirection page, with message about redirecting in 5 seconds and then it moves to `http://localproject.net/tools/webinterface/`, which is **404**. When I access subfolder like `http://localproject.net/assets` it access `$document_root/assets` properly, but simply accessing `$document_root` via `http://localproject.net` is not possible.

I cannot find configuration for the redirection page. I looks like it points to `www/index.html` file, but even if I delete that file, the redirection page is still there and I cannot get over it.

Am I missing something? I run WPN-XM 0.8.0 on Win8.1x64. After any change I do restart NginX, the virtual host works, but not when I want access its root url.

**Comment by jakoch** [comment]
Hey Racochejl,

ok, i will take look.

Steps to reproduce the issue:

1. added `localproject.net` hosts
2. placed config content into `domains-enabled\project.conf`
3. created project at /www/project/dist
   - added `/www/project/dist/index.php` with `<?php echo getcwd();`
4. restart server
5. testing access to http://localproject.net - works

6. webinteface: http://localhost/tools/webinterface/ correctly shows `project` under "Projects"
7. accessing http://localhost/project/ - works and leads to /www/projects, listing the directory content

The configuration you posted works for me. I can not reproduce the issue.

This could be a browser cache issue. My suggestion is to clean the cache.
Please test this and provide feedback.

> I cannot find configuration for the redirection page. I looks like it points to www/index.html file, but even if I delete that file, the redirection page is still there and I cannot get over it.

Yes, the redirection to the webinterface is started by `www/index.html`.
The configuration is done in the main server block of `nginx.conf`, see https://github.com/WPN-XM/WPN-XM/blob/master/configs/nginx.conf#L93
Nginx will look inside `www/*` for the index files in the specified order.
This directive has no influence on projects with their own `root` directive.

Regards, Jens

**Comment by Racochejl** [comment]
Hello jakoch,
sure, it was browser cache. Damn cache! Always forget to clear it and then search for complicated solution. Thank you for quick reply, my problem is thereby solved.

**Comment by jakoch** [comment]
:+1: Glad you solved it.

If you find other issues with WPN-XM or have ideas for features or improvements please let me know.

**Comment by brunowego** [comment]
:+1:
