### ISSUE TITLE
using sqlite3 

### ISSUE THREAD

**Issue by qsab3d0r** [WPN-XM/WPN-XM#328]
any ideas how to make work sqlite3 i trying commenting and discommenting and seems nothing to work

**Comment by jakoch** [comment]
Hello qsab3d0r

You need to enable the PHP extension `php_sqlite3.dll` in your `php.ini`.
Then restart the PHP daemon.

```
<?php
$db = new SQLite3('mysqlitedb.db');

$results = $db->query('SELECT * FROM mytable');
while ($row = $results->fetchArray()) {
    var_dump($row);
}
```

Regards, Jens

**Comment by jakoch** [comment]
Ok, 5 days no feedback. 
Closing the issue.
