### ISSUE TITLE
Nginx Error: The process failed to start

### ISSUE THREAD

**Issue by brunowego** [WPN-XM/WPN-XM#330]
```
Nginx Error: The process failed to start.
Either the invoked program is missing, or you may have insufficient permissions to invoke the program.
```

I run the software with admin privileges.

![bug](https://cloud.githubusercontent.com/assets/441774/6485208/c9e2b79c-c260-11e4-8ecc-7d8082dc4baa.gif)

**Comment by jakoch** [comment]
Hey Bruno!

Thank you for the report! 

a) Does nginx start via `start-wpnxm.bat`?

b) Can you give the latest version (0.8.1-alpha) of the SCP a try?
https://github.com/WPN-XM/server-control-panel/releases/download/0.8.1-alpha/wpnxm-scp-x64.zip
Installation: just delete old wpn-xm.exe and unzip the files to the root folder of the server stack.
I hope all dependencies are there, if not please report.

**Comment by brunowego** [comment]
Have a issue with the name of folder, now it's called `nginx-VERSION`. Solved when change the name of folder to `nginx`.

**Comment by jakoch** [comment]
Ah! Yes, the nginx.zip contains a versionized folder name and during installation the folder is extracted and then renamed - now: if that fails you end up with "nginx-1.2.3".
So this might indicate an error in the installer - and i hope it's already fixed for the next release.
I can not remember - to many things modified.

**Comment by brunowego** [comment]
Nice, thanks a lot @jakoch for your attention.

**Comment by jakoch** [comment]
If you have ideas for features or find any glitches, please report them. 
Thanks for trying WPN-XM.

**Comment by klonos** [comment]
Yeah, I have a ```nginx``` as well as an ```nginx-1.7.5``` folder. So, I didn't have the reported issue. I deleted the versioned one and kept the plain ```nginx```. I'm not sure how the versioned one creeped in there. Could be subsequent (re)installations.

**Comment by jakoch** [comment]
This is happening one time too often. 

The installation of nginx is done in two steps:
1. nginx.zip is extracted into the bin folder: this creates `nginx-VERSION`
2. then `nginx-VERSION` simply renamed to `nginx`with a `move /Y` cmd, replacing old files in then nginx folder

If an installation ends up with a `component-VERSION` folder inside the bin folder, then the move operation failed for whatever reason.

**Comment by luizbills** [comment]
+1

**Comment by jakoch** [comment]
@luizbills Hey Luiz, do you have the same issue?

**Comment by luizbills** [comment]
@jakoch Yes.
When I installed has created the folders `nginx` and `nginx-VERSION`.
I use windows 7 64 bits.

**Comment by jakoch** [comment]
I've changed the extraction and folder creation for Nginx and tested the `full-installer-56-x64`. 
This looks ok: ![nginx-version](https://cloud.githubusercontent.com/assets/85608/9413437/20bbacc0-4832-11e5-99d6-04cbdab9ccf9.png)

Closing. If the issue pops up again. Reopen a new ticket please.
