### ISSUE TITLE
Change localhost address

### ISSUE THREAD

**Issue by brunowego** [WPN-XM/WPN-XM#331]
By default, when run server opens `http://localhost`, but in my case I working at restrict network and `localhost` is blocked. Then every time this open I need change the address. Have any way to change it?

**Comment by jakoch** [comment]
No, not yet. It's hardcoded in the batch files and the SCP, see:
- start-wpnxm.bat (https://github.com/WPN-XM/WPN-XM/blob/master/startfiles/start-wpnxm.bat#L69)
- SCP: https://github.com/WPN-XM/server-control-panel/blob/master/src/tray.cpp#L120

Changing the localhost address might be useful for others, too. 
For the batch file, i guess, the file is easy enough to edit manually.
But, the SCP would need a new config directive to allow this.

- [ ] add configuration directive for the "localhost" URL

**Comment by brunowego** [comment]
Thanks again @jakoch :+1:
