### ISSUE TITLE
select new admin-ui for mongodb

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#345]
The rockmongo project seems dead.
website is down.
1.1.8 is only in the repo, but not on github releases.
our crawler can't pick this up.
i will not switch this to githubs archive.zip.

we need to select a new, better maintained admin interface for mongo
http://docs.mongodb.org/ecosystem/tools/administration-interfaces/#admin-uis

a php based solution would be nice.
but a binary application could fit,too. maybe robomongo?

i'm open for suggestions.

**Comment by anton-petrov** [comment]
My suggestion is Robomongo - http://robomongo.org/
