### ISSUE TITLE
provide extra download page for all the components

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#348]
This will be an extended version of the "registry" display on our website.
The software registry allows to fetch component name, url and version.
It should be easier to fetch a specific version via our website.

- [x] create a download page listing all components
- [x] show latest version for direct download
- [x] show dropdown, listing all versions for selective download

add maybe some sugar on top:
- [ ] SEO
- [ ] machine readable JSON+LD download descriptions, like on the frontpage
- [ ] high quality logos for the components or companies producing the components

**Comment by jakoch** [comment]
The download page for components has landed: http://wpn-xm.org/components.php

**Comment by klonos** [comment]
Very helpful. Thanx @jakoch!
