### ISSUE TITLE
PostgreSQL port not shown in SCP.

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#355]
Latest 0.8.1 x64 version on Win8.

**Comment by jakoch** [comment]
The new postgresql settings were missing in the default wpn-xm.ini file.

Fixed with this commit https://github.com/WPN-XM/WPN-XM/commit/7f856712f68303d95e3b1e340d5908588ab4f85b#diff-0325fcc7907da19bf1a9ace7ec983941R52

**Comment by klonos** [comment]
Confirming fixed in 0.8.2. Thanx!

**Comment by jakoch** [comment]
ah, good. finally some progress.
