### ISSUE TITLE
Internal error: ExtractTemporaryFile: The file "phpmyadmin.zip" was not found.

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#357]
This happened with the WPNXM-0.8.2-Full-Setup-php55-w64.exe:

```
---------------------------
Setup WPN-XM 0.8.2
---------------------------
Runtime Error (at 92:14319):

Internal error: ExtractTemporaryFile: The file "phpmyadmin.zip" was not found.
---------------------------
OK   
---------------------------
```

**Comment by jakoch** [comment]
Correct. https://travis-ci.org/WPN-XM/WPN-XM#L3607
Download failed. File was not included.

**Comment by klonos** [comment]
Ah, ok. Are you going to rebuild and re-upload? If so, can you please let me know so I can download afresh and give it another go?

**Comment by jakoch** [comment]
Yes, i will delete v0.8.2 and force an update. Working on it.
You might also test the installation with de-selected "phpmyadmin".
I hope that we addressed (at least some of) the other issues.

**Comment by klonos** [comment]
>You might also test the installation with de-selected "phpmyadmin".

Doing it now...

**Comment by jakoch** [comment]
Ok, fixed. 
The next build uses v4.3.11.1 via http://wpn-xm.org/get.php?s=phpmyadmin
