### ISSUE TITLE
Left-over folders and files after uninstallation.

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#358]
Here's what's left after full uninstall:

```
C:\WPN-XM\bin
C:\WPN-XM\bin\memcached
C:\WPN-XM\bin\memcached\memcached-x86
C:\WPN-XM\bin\memcached\memcached-x86\pthreadGC2.dll
C:\WPN-XM\temp
C:\WPN-XM\temp\.htaccess
C:\WPN-XM\www
C:\WPN-XM\www\backdrop
C:\WPN-XM\www\backdrop\files
C:\WPN-XM\www\backdrop\files\.htaccess
C:\WPN-XM\www\backdrop\files\translations
C:\WPN-XM\www\backdrop\files\translations\.htaccess
C:\WPN-XM\www\customer
C:\WPN-XM\www\customer\sites
C:\WPN-XM\www\customer\sites\default
C:\WPN-XM\www\customer\sites\default\files
C:\WPN-XM\www\customer\sites\default\settings.php
C:\WPN-XM\www\customer\sites\default\files\.htaccess
C:\WPN-XM\www\project
C:\WPN-XM\www\project\adaptive
C:\WPN-XM\www\project\fixed
C:\WPN-XM\www\project\responsive
C:\WPN-XM\www\project\adaptive\sites
C:\WPN-XM\www\project\adaptive\sites\default
C:\WPN-XM\www\project\adaptive\sites\default\settings.php
C:\WPN-XM\www\project\fixed\sites
C:\WPN-XM\www\project\fixed\sites\default
C:\WPN-XM\www\project\fixed\sites\default\settings.php
C:\WPN-XM\www\project\responsive\sites
C:\WPN-XM\www\project\responsive\sites\default
C:\WPN-XM\www\project\responsive\sites\default\settings.php
```

**Comment by klonos** [comment]
...could be because these files have a read-only attribute. Perhaps a good idea to remove the flag before uninstallation/deletion process.

**Comment by jakoch** [comment]
The memcached extraction seems wrong, too
Read-Only Flag removal is in place, see https://github.com/WPN-XM/WPN-XM/blob/master/installers/full-php54-w32.iss#L1204
But for `bin\memcached\pthreadGC2.dll` and not `memcached\memcached-x86`...

- [ ] check memcached extraction
- [ ] set read-only flag on projects in www folder before

**Comment by klonos** [comment]
OK, another minor bug then. Glad we are finding and squashing these one-by-one. These might prove to cause other issues in the future.

**Comment by jakoch** [comment]
Yes, things quickly add up and make the impression that the stack is not in a good condition.

One other issues witch randomly occurs is the this folder renaming problem.
I have no clue, why this operation fails... maybe disk i/o or AV scans.. 
Out of curiosity i could add sleep(500) before and after the command to give the system some time.
I have no idea on how to address this issue.
Exec(hideConsole, 'cmd.exe /c "move /Y ' + appPath + '\bin\memcached-x86 ' + appPath + '\bin\memcached"', '', SW_SHOW, ewWaitUntilTerminated, ReturnCode);

**Comment by jakoch** [comment]
I removed the read-only flag removal for the memcached file.
I added removal of read-only flag for all files and folders in the server dir.

**Comment by jakoch** [comment]
Files for v0.8.2 removed - rebuild in progress: https://travis-ci.org/WPN-XM/WPN-XM/builds/54416291
I hope the downloads work and the upload, too. 
I'm off. 3:30 am, need some sleep.

**Comment by klonos** [comment]
> I'm off. 3:30 am, need some sleep.

Yes you need some sleep(500) too :stuck_out_tongue:

**Comment by jakoch** [comment]
hehe - vacation(2w) would be nice^^ 

v0.8.2 is now rebuild - https://github.com/WPN-XM/WPN-XM/releases/tag/v0.8.2

**Comment by jakoch** [comment]
Tested the uninstallation with some read-only folder/files with WPNXM-0.8.2-Lite-Setup-php56-w64.exe
The problem is still there...

**Comment by klonos** [comment]
>  more sleep and vacation(2w) would be nice^
:smile: 

Yeah, but I was thinking that perhaps the contents of the ```www``` directory should not be touched or at least everything else other than ```hello_world``` and ```tools```. As it is now, we leave it up to the end user to back up their data and that's not good. Fair enough, we have the warning in place, but people are creatures of habit and simply click through the installer/uninstaller without paying attention to the messages. They are all "Next, next, next, ok, ok, ok, finish" if you know what I mean.

Do you have any plans to keep the ```www``` directory in place for upgrades? If so, you should also consider the databases (for example the ```\bin\mariadb\data``` folder etc).

**Comment by jakoch** [comment]
Yes, with the first versions the user created files were left after an uninstallation.
But that means that a user has to delete the main folder himself else it would remain.

> we leave it up to the end user to back up their data and that's not good.
They should care about their projects and databases and take the steps to back them up properly.
I can only provide the framing and some tools to ease that job - prepare a backup script, etc.

I changes made are
- complete uninstallation (leave no trace, no further interaction)
- warning box that the projects folder gets deleted, too
- backup script to pull user files out of projects and bin/components folders into a backup folder

**Comment by Kogurex** [comment]
Now in 0.8.2 it just left "server" folder without files.

**Comment by jakoch** [comment]
```
      // Deletes the application directory and everything inside it.
      // This function will remove directories that are reparse points,
      // but it will not recursively delete files/directories inside them.
      DelTree(ExpandConstant('{app}'), True, True, True);
```
Change: https://github.com/WPN-XM/WPN-XM/commit/c581976ca54cfd64a5508792557dec57ff03a4ef

In other words: deletes the application directory and everything inside it, except there is a symlink or reparse point inside one of the folders.

**Comment by klonos** [comment]
> - warning box that the projects folder gets deleted, too

We still have that in place. Right?

**Comment by jakoch** [comment]
Yes, the message box is in place, see for instance
https://github.com/WPN-XM/WPN-XM/blob/master/installers/full-php55-w32.iss#L1554-1563
Only the behavior of the delete function changed.

**Comment by klonos** [comment]
Thanx for taking the time to clarify this.
