### ISSUE TITLE
Installer window position locked.

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#359]
The installer window locks its position and cannot be dragged. One might want to get it out of the way (on a second monitor for example). If there is no specific reason for having it so, can you make it so that it is draggable? Thanx.

**Comment by jakoch** [comment]
Yes, this is annoying, but i don't know how to change it, yet.
When no child processes are executed, then the window is moveable.
The movement is not possible during the execution of child processes.

**Comment by klonos** [comment]
Fair enough. This is a trivial feature request. Other things (bugs) are more important and you can leave this one for when you have the time/energy. For now, if one wants to get the window out of the way, they can always minimize/show desktop.

**Comment by fungi8210** [comment]
Did you get this solved? I'm having the same issue with my installer too using InnoSetup.

**Comment by jakoch** [comment]
I'm not working on this issue at the moment.
As you can see, the research i did a month ago shows how to do it.
Combine  InnoCallback.dll with an external unpacker. 
This will not only make the Innosetup windows moveable again,
but allows to fetch the "extraction progress" and "current file" being extracted.

**Comment by jakoch** [comment]
This issue might have made the impression of a trivial feature request,
but is was very tricky to implement. Not easy or trivial at all.
I guess, this new approach will set the new standard for unzipping with InnoSetup.
(At least, until someone figures out how to work with the 7zip API and fetch the progress via a callback.)

You find the `unzip.iss` over at Github Gists: https://gist.github.com/jakoch/33ac13800c17eddb2dd4
with some usage instructions on top.

A patch for the WPN-XM installers is incoming...

**Comment by klonos** [comment]
Thanx! :+1:
