### ISSUE TITLE
Only show the log file icons/buttons in SCP if the respective file exists.

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#360]
As it is now, these icons are shown even if the respective log file has not been created yet. When clicking these, there is an error thrown saying that the file does not exist. Perhaps we could have the buttons be grayed-out and disabled instead with a hover-over tip saying something along the lines of "no log file created yet".

Thanx for considering this. It would be a minor UX improvement, but I understand that there are other serious features to be implemented and bugs to be fixed first.

**Comment by klonos** [comment]
Related: #356

**Comment by jakoch** [comment]
Every little detail counts. This idea makes sense: disabled button = no pointless click.

**Comment by klonos** [comment]
Yeah, I am no UX expert, but this is a no-brainer. It would be nice to have.

**Comment by klonos** [comment]
Thanx.

**Comment by jakoch** [comment]
You are welcome. 

I'm not sure if its the best way to implement it, but now whenever the Mainwindow is displayed the file exist check is done and the button state is changed accordingly. The "File not found" message box remains in place to catch cases, where the MainWindow is shown, Buttons get enabled, but the file is deleted (for whatever reason), before the Button was clicked.

When you have some more ideas for the stack on your mind, please post them.

**Comment by klonos** [comment]
> The "File not found" message box remains in place to catch cases, where the MainWindow is shown, Buttons get enabled, but the file is deleted (for whatever reason) before the Button was clicked.

Good thinking there. Would not expect anything less from you. :+1: 

> When you have some more ideas for the stack on your mind or ran into issues lately, please post them.

Will do. Thanx again.
