### ISSUE TITLE
installation problem ?[0.8.2]

### ISSUE THREAD

**Issue by serhatdurum** [WPN-XM/WPN-XM#362]
Hi there,

Thanks for work.I tried to install 0.8.2 standard setup with php56 w64 but when setup finish, i got error "wpn-xm.exe not found" and when i'm looking in server folder there is no exe also in php and nginx folder there are no exes.

Then i'm trying to webinstaller, setup frozed %80.

Is it just issue on me ? Btw Win8.1 64bit.
Thanks

**Comment by klonos** [comment]
Hello @serhatdurum, when did you download the installer? There ware a few issues with the packaging of some components and the 0.8.2 installation files were rebuilt a few hours ago. Perhaps re-download and try again?: https://github.com/WPN-XM/WPN-XM/releases/tag/v0.8.2

**Comment by serhatdurum** [comment]
@klonos thanks for qucik reply.

i re-downloaded with your comment link.and there are images.

![selection](https://cloud.githubusercontent.com/assets/7244399/6656482/ecebead8-cb34-11e4-8d20-439c2ac53ff7.jpg)

![progress](https://cloud.githubusercontent.com/assets/7244399/6656483/eceef110-cb34-11e4-8a6e-97aafc7ca8a2.jpg)


![frozen](https://cloud.githubusercontent.com/assets/7244399/6656481/ecea4bd8-cb34-11e4-9bf3-9b8af5659382.jpg)


![folders](https://cloud.githubusercontent.com/assets/7244399/6656480/ece967ea-cb34-11e4-89c5-809c626bca07.jpg)

**Comment by serhatdurum** [comment]
and i downloaded this time full stack and got error also like this,
![errror](https://cloud.githubusercontent.com/assets/7244399/6656505/758ff672-cb35-11e4-9db9-48590a99c18f.jpg)

**Comment by jakoch** [comment]
Hey Serhat, i'm on it. 

Downloading and trying to reproduce the errors.
https://github.com/WPN-XM/WPN-XM/releases/download/v0.8.2/WPNXM-0.8.2-Standard-Setup-php56-w64.exe

According to the Travis buildlog the packaging of the Standard installer was ok, all components included and deployment to github finished. but lets find out

**Comment by serhatdurum** [comment]
@jakoch Thanks.. i opened issue because of that, i saw build passing badge and nobody issued before, so i think there is an specific issue for me.Can we see setup log or sth else?

**Comment by jakoch** [comment]
Thanks for reporting. This is the second release on Travis. 
I hope that things stable-ize and can release fixes and update component versions faster.

You find the build log here: https://travis-ci.org/WPN-XM/WPN-XM/builds/54416291

**Comment by serhatdurum** [comment]
@jakoch i tried now WPNXM-0.8.0-Lite-Setup-php56-w64.exe succesfully installed but, my php version is 5.5.17 and nginx 1.7.5 seem on control panel.

**Comment by jakoch** [comment]
Hmm, ok - but 0.8.0 is outdated.
This would be a better choice: https://github.com/WPN-XM/WPN-XM/releases/download/v0.8.2/WPNXM-0.8.2-Lite-Setup-php56-w64.exe

**Comment by jakoch** [comment]
Ok, i've tested the following installers
- WPNXM-0.8.2-Webinstaller-Setup-php56-w64.exe - can not reproduce. No problems.
- WPNXM-0.8.2-Lite-Setup-php56-w32.exe - can not reproduce. No problems.
- WPNXM-0.8.2-Standard-Setup-php56-w64.exe - in progress

**Comment by serhatdurum** [comment]
@jakoch thanks for effort..
i wanted to try old version about setup problem but it worked without error.

and now, tried WPNXM-0.8.2-Lite-Setup-php56-w32.exe got error again.

**Comment by jakoch** [comment]
Ok, tested Standard, too. Works.
I can not reproduce this installation issue on my machine.
It might be an individual issue.

Is there any other software installed which might influence the installation process?

**Comment by serhatdurum** [comment]
@jakoch nope.i installed windows today.I guess there is an extract problem for 0.8.2.because 0.8.0 worked.And its'nt just wpm exe.Also mariadb,nginx and php folder are empty.

 Can i see get log during setup or after?

Thanks again for your affordable interesting. :wink:

**Comment by jakoch** [comment]
Please take a look at the `/logs` folder after the failed installation.
You should find a file, like `Setup Log 2015-03-15 #NUM.txt`.
Please upload it to a pastebin somewhere so that i can take a look.

A successful webinstaller log looks like this one: http://paste.debian.net/hidden/89f7b9ec/

**Comment by anton-petrov** [comment]
I also have some errors while installing 0.8.2. It's part of install log:

2015-03-15 21:45:45.879   Run as: Current user
2015-03-15 21:45:45.879   Type: Exec
2015-03-15 21:45:45.879   Filename: c:\server\bin\perl\relocation.pl.bat
2015-03-15 21:45:45.879   Exception message:
2015-03-15 21:45:45.879   Message box (OK):
                          Unable to execute file:
                          c:\server\bin\perl\relocation.pl.bat
                          
                          CreateProcess failed; code 267.
                          The directory name is invalid.
2015-03-15 21:45:54.198   User chose OK.
2015-03-15 21:45:54.198   -- Run entry --
2015-03-15 21:45:54.198   Run as: Current user
2015-03-15 21:45:54.198   Type: Exec
2015-03-15 21:45:54.198   Filename: c:\server\bin\perl\update_env.pl.bat
2015-03-15 21:45:54.198   Exception message:
2015-03-15 21:45:54.198   Message box (OK):
                          Unable to execute file:
                          c:\server\bin\perl\update_env.pl.bat
                          
                          CreateProcess failed; code 267.
                          The directory name is invalid.
2015-03-15 21:45:55.560   User chose OK.
2015-03-15 21:45:55.561   Visual C++ 2012 Redistributables 
2015-03-15 21:45:55.561   are already installed.
2015-03-15 21:45:56.059   Need to restart Windows? No
2015-03-15 21:45:58.339   -- Run entry --
2015-03-15 21:45:58.339   Run as: Original user
2015-03-15 21:45:58.339   Type: Exec
2015-03-15 21:45:58.339   Filename: c:\server\wpn-xm.exe
2015-03-15 21:45:58.339   Exception message:
2015-03-15 21:45:58.340   Message box (OK):
                          Unable to execute file:
                          c:\server\wpn-xm.exe
                          
                          CreateProcess failed; code 2.
                          The system cannot find the file specified.

**Comment by serhatdurum** [comment]
@jakoch my setup log http://paste.debian.net/161416/ can you see sth wrong ?

**Comment by anton-petrov** [comment]
As a result of install, had only ~12mb folder 'c:\server'

**Comment by anton-petrov** [comment]
My log: http://paste.debian.net/161417/

**Comment by jakoch** [comment]
@serhatdurum Log is ok. Nothing special.

@anton-petrov Thanks for reporting. This log indicates an extraction error of `perl.zip` and `wpnxm-scp.zip`.

I'm a bit clueless on the real source of the error.
For a successful extraction the files 7z.exe and RunHiddenConsole.exe are important.
It's basically hidden 7z extractions and cmd.exe invocations with copy, move or rename operations.

**Comment by anton-petrov** [comment]
Also, installer successfully created temporary 'C:\Users\Administrator\AppData\Local\Temp\is-2MEGU.tmp', which contains all archives, including 7z.exe, etc.

**Comment by serhatdurum** [comment]
@anton-petrov in bin folder will there any exe? in php,nginx or mariadb.. your log looks like me

**Comment by jakoch** [comment]
Yes, exactly and the DoUnzip() command in the installer would show an Error Message Box,
in case 7z or the file to extract would be missing.
That leads to the pure unzip cmd: `tempfolder\7z.exe x sourcefile -o targetdir -y`.
https://github.com/WPN-XM/WPN-XM/blob/master/installers/full-php56-w64.iss#L695

Out of curiosity does running the installer in compatiblity mode change a thing?
I doubt it, but maybe it's a permissions, UAC or compatiblity 32bit / 64bit problem.

**Comment by serhatdurum** [comment]
@jakoch in bin/tools there is no 7z.exe it contains "hosts,process,runhiddenconsole and psvince.dll" 
but the log says 

"2015-03-15 21:24:27.656   Dest filename: C:\server\bin\backup\7z.exe
2015-03-15 21:24:27.656   Time stamp of our file: 2015-03-15 02:42:14.000
2015-03-15 21:24:27.656   Installing the file.
2015-03-15 21:24:27.694   Successfully installed the file."

my uac is off and tried compatibility mode.

**Comment by jakoch** [comment]
This is ok, Serhat.
The 7z.exe and RunHiddenConsole.exe are only extracted to the temporary folder.
`/bin/backup/` should contain a 7z.exe file.

**Comment by jakoch** [comment]
![win8-64-error](https://cloud.githubusercontent.com/assets/85608/6658133/3e73eb32-cb60-11e4-94d7-0b1d2ee6a384.png)

`ShellExecuteEx Error - System cannot find the path specified.`

**Comment by jakoch** [comment]
Replaced 7zip.
Forcing a rebuild of v0.8.2.

**Comment by jakoch** [comment]
Replaced "7z" with "7za".
Forcing a rebuild of v0.8.2 - https://travis-ci.org/WPN-XM/WPN-XM/builds/54506546
Downloads: https://github.com/WPN-XM/WPN-XM/releases/tag/v0.8.2
Give this file a try for testing: https://github.com/WPN-XM/WPN-XM/releases/download/v0.8.2/WPNXM-0.8.2-Lite-Setup-php56-w32.exe

et voila...
![install-ok](https://cloud.githubusercontent.com/assets/85608/6659343/e2f9a6a6-cb83-11e4-908e-783d890b7c59.png)

**Comment by jakoch** [comment]
Got feedback from Anton.
The issue is resolved.
Guys, thank you again for reporting the issue.

**Comment by serhatdurum** [comment]
@jakoch thanks for feedback.

I tried litesetup w64 it seems there are 2 nginx in bin folder pic are here.But w32 works perfect! thanks.

![nginx](https://cloud.githubusercontent.com/assets/7244399/6663259/7d163a94-cbcd-11e4-917d-b03e6cee39ee.jpg)
![nginx2](https://cloud.githubusercontent.com/assets/7244399/6663258/7d14f94a-cbcd-11e4-9657-7f313bf3e8c7.jpg)

**Comment by jakoch** [comment]
This "component-version" extraction error happens way too often.
To resolve the error manually: copy all files from "nginx-1.7.10" to "nginx" and delete "nginx-1.7.10".

The installer does three things: 
1. /bin/nginx is created and default configs are copied into the folder
2. nginx.zip is extracted to /bin. nginx.zip brings it's own versionized toplevel folder: nginx-version. 
3. the "nginx-version" folder is renamed to nginx via a simple `move` with forced overwrite, see https://github.com/WPN-XM/WPN-XM/blob/master/installers/full-php54-w32.iss#L1145

This third steps is failing.
