### ISSUE TITLE
WPИ-XM Control Panel all buttons permanently redirecting to web interface on port 80

### ISSUE THREAD

**Issue by anton-petrov** [WPN-XM/WPN-XM#363]
When changing nginx port form standard 80 to, for example, 81, the  WPИ-XM Control Panel's 'web interface' button and other button's all the same open's localhost:80, instead of opening localhost:81. Maybe it is need to add some parsing to nginx.conf?

P.S.: thanks for fixing bug with 7z.exe on win8, now 0.8.2 build works fine on windows server 2012 ;)

**Comment by jakoch** [comment]
> P.S.: thanks for fixing bug with 7z.exe on win8, now 0.8.2 build works fine on windows server 2012 ;)

Still not sure, what the real difference between 7z and 7za is 
and why 7z works on WinXP & Win7 and stops working on Win8. 
But anyway, it's working now. Thank you very much for reporting it.

> Maybe it is need to add some parsing to nginx.conf?

You are right, Anton.
The port needs to be fetched from the main server block of nginx.conf.
And all the links need to take these ports into account.
Currently the values for the server ports and the button links are hardcoded.
It's already on my roadmap to add a port configuration tab to the configuration dialog, see #327.
The port values are then written to nginx.conf and wpn-xm.ini (as the central config file).

**Comment by jakoch** [comment]
Closed, because this issue is part of the work of issue #327.
