### ISSUE TITLE
WPN-XM Server Control Panel Crash at startup

### ISSUE THREAD

**Issue by belbert** [WPN-XM/WPN-XM#365]
### Symptom
Crash of WPN-XM Server Control Panel 0.8.0
at the QT5 Library when `autostartdaemons=1`
Setting `autostartdemons=0` fixes the crash

### System
Win 7 64bit latest updates
Autostart: Default (nginx,php,mariadb)

### Links
Also linked at http://stackoverflow.com/q/27867506/3332686
by another user

Regards U101

---
And keep up the good work :)

**Comment by ProcTrap** [comment]
found the regarding issue tracker..

**Comment by jakoch** [comment]
v0.8.0 is outdated. 
Please update the stack or just the server control panel.
https://github.com/WPN-XM/server-control-panel/releases/tag/0.8.1

**Comment by nasl** [comment]
I am still getting the same problem on 0.8.1

**Comment by jakoch** [comment]
@nasl Is this related to `autostartdemons`? Do you have all components installed (full) or are some missing (postgres not installed?)?

**Comment by nasl** [comment]
yes, postress, perl, rediska are missing and maybe 1-2 others
p.s. this is on 0.8.1. + nnnn release, the latest on the web site

**Comment by jakoch** [comment]
> p.s. this is on 0.8.1. + nnnn release, the latest on the web site

Thank you for the feedback.
I think it crashes because the SCP tries to execute a not existing daemon (version lookup maybe).
I will try to reproduce this with a minimal set of components, e.g. Lite installer only.

**Comment by nasl** [comment]
it may be related, as in ini file I have ilens with mongo and postgre, but I opted not to install anything related to them

**Comment by Kogurex** [comment]
So with this. Pressing nginx start or all daemons start...
![image](https://cloud.githubusercontent.com/assets/11504405/7301584/f6c4088a-e9b9-11e4-88de-3566b75bacfc.png)

**Comment by jakoch** [comment]
@Kogurex 
Which version is this?  v0.8.2? Server-Control-Panel 0.8.1-githash? 
Is Nginx missing in the bin folder (`/bin/nginx/nginx.exe`)?

**Comment by Kogurex** [comment]
I reinstalled it about 8 times, now works, but analyzing it, it installed nginx in a different folder called like nginx_x.x.x (Where x's are numbers). I had Blackberry Link (That uses nginx in PeerManager Process) and uninstalled it, trying to make XPN-XM work. It appears to be solved. Version below. 
![clipboard01](https://cloud.githubusercontent.com/assets/11504405/7303365/804100e8-e9c6-11e4-9bed-293a9454a82e.jpg)

**Comment by jakoch** [comment]
> I reinstalled it about 8 times

oh man, i'm sorry. please report the bugs or problems you encounter. i will address them, this helps all.

This "nginx_versionnumber" error is poping up from time to time.
The reason for this error is: nginx.zip is extracted to a "nginx_versionfolder", then i rename the folder to just "nginx" - but the rename operation fails "sometimes", but way to often!
Need to rework that, too. But this is unrelated to the SCP.

**Comment by jakoch** [comment]
> EDIT: Starting all daemons, crashed, running as admin, all Win7 Upgrades done...

New release incoming...

**Comment by jakoch** [comment]
Here we go: https://github.com/WPN-XM/server-control-panel/releases/tag/0.8.2
- https://github.com/WPN-XM/server-control-panel/releases/download/0.8.2/wpnxm-scp-x86_64_boxed.zip
- https://github.com/WPN-XM/server-control-panel/releases/download/0.8.2/wpnxm-scp-x86_boxed.zip

I've tested this against a Lite Installer-v0.8.1-PHP55-x86 and i couldn't reproduce the crash.
Please give some feedback..

**Comment by Kogurex** [comment]
I forgot to tell that i've installed with WPNXM-0.8.2-Full-Setup-php56-w64.exe
I'll try Lite and will do feedback...

**Comment by jakoch** [comment]
@Kogurex Looks good :D 
Thank you for trying out this new stack and reporting issues to improve it.

**Comment by belbert** [comment]
@Kogurex exact the same error message appeared also to my colleague, with the minified version containing only nginx, php & mariadb.
Which is interesting, because I blamed his PC/configuration for it and downloaded the full wpn-xm stack, which fixed it.

**Comment by Kogurex** [comment]
@nasl try to overwrite the panel that @jakoch sent to us, migh solve completely this issue. At least, for x86_64 packages it worked like a charm!
