### ISSUE TITLE
Webinterface: PHP Extensions count not updated after extension enabling/disabling.

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#366]
When you enable or disable a PHP extension in Configuration >> PHP Extensions, the *(x of y loaded)* text does not get updated. You need to refresh the page to see the change take effect.

....which also reveals another minor issue: upon page refresh, the selected tab is not "remembered" - you are always taken to the help tab and need to re-select the PHP Extensions tab.

**Comment by jakoch** [comment]
Confirmed. It's an ajax issue.
- [ ] ajax response needs to include the extension counter as part of the response (json) and update the dom
- [ ] remember tab on page refresh

**Comment by klonos** [comment]
...opened separate issue for the page refresh thing.

**Comment by jakoch** [comment]
Implemented.
