### ISSUE TITLE
Configure Nginx as reversed proxy in this stack

### ISSUE THREAD

**Issue by nntoan** [WPN-XM/WPN-XM#368]
Hello,

I want to install Apache into this server stack, is it possible to do?

**Comment by jakoch** [comment]
Hey!

Yes, it possible. I will describe the steps roughly:

- install Apache manually, maybe into `bin/apache`
- adjust it's configuration to start serving pages from `server/www` at a specific port, let's say `8080`
- adjust the batch files for starting and stopping wpn-xm, to include a apache start and apache stop
- now Apache should start serving dynamical webpages at port `8080`
- then configure Nginx to acts as the reverse proxy
  - that means that Nginx servers static files 
  - forwards to Apache for the dynamically files via proxy_pass to `8080`

```
server {
        listen   80; 

        root ... 
        index index.php index.html index.htm;

        server_name example.com; 

        location / {
        try_files $uri $uri/ /index.php;
        }

        location ~ \.php$ {        
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:8080; // forward to apache for dynamic pages
        }

         location ~ /\.ht {
                deny all;
        }
}
```

Sidenote: The server-control-panel will not recognize Apache. So you can't start and stop things from there.

**Comment by jakoch** [comment]
No feedback. Seems solved. 
If you have further questions, feel free to ask.
Closing.

**Comment by messala** [comment]
@jakoch Just adding, to complete the Apache configuration, it's necessary to set the php handler properly at conf file. Also, for Apache 2 module, I had to download the php 7 TS version to copy the php7apache2_4.dll and I placed it at php folder.

Sample of handler:
```
AddHandler application/x-httpd-php .php
AddType application/x-httpd-php .php .html
LoadModule php7_module "c:/server/bin/php/php7apache2_4.dll"
PHPIniDir "c:/server/bin/php"
```

Sorry to resurrect this post.

**Comment by jakoch** [comment]
No problem. Thank you for the comment.
I will add this to the documentation, new issue is: https://github.com/WPN-XM/WPN-XM/issues/656
