### ISSUE TITLE
%~dp0 instead %cd%

### ISSUE THREAD

**Issue by sim2github** [WPN-XM/WPN-XM#370]
Beter to use `%~dp0` - disk+path of script instead `%cd%` - current location (like `pwd`:UNIX ) 
because of `c:\server\www>c:\server\start-wpn-xm.bat` not working.
**Option:** Please short up script names to start, stop, restart or wwwstart, wwwstop, etc - its more easy to type in console (whatever name of your product in every header of bat file).

**Comment by jakoch** [comment]
Good catch! I will change it.

- [ ] switch from %cd% to %~dp0
- [ ] shorten batch filenames
