### ISSUE TITLE
[feature proposal]  Integrated Command Line Interface

### ISSUE THREAD

**Issue by sim2github** [WPN-XM/WPN-XM#371]
I`d like to introduce more friendly CLI [ConEMU](http://sourceforge.net/projects/conemu/)

That helps me a lot on Windows to be more closer to UNIX (msysgit)

[bash_profile - msysgit - WPN-XM](https://gist.github.com/337cf2dccb8cfc39bc1a) - `C:\server\bin\git\etc\bash_profile ` - my aliases and PATH  combining all togather if any one interesting

```cmd
:start-shell
    echo Opening www folder in console
    %HIDECONSOLE% %~dp0\bin\tools\ConEmu\ConEmu.exe /cmd %~dp0\bin\git\git-bash.bat -cur_console:C:%~dp0\bin\git\etc\git.ico 
goto END
```

**BTHW:** Nice work!!!

**Comment by jakoch** [comment]
Hey Alex, 

adding ConEmu is a great idea. Thank you very much for contributing your bash_profile.

At the moment i'm looking at Cmder - https://github.com/bliker/cmder.
That's a spiced up version of ConEmu with Themes on top + [Clink](http://mridgers.github.io/clink/) + mysysgit. What do you think about it?

> BTHW: Nice work!!!

Glad you like the stack.

Regards, Jens

**Comment by sim2github** [comment]
Cmder+Clink is interesting idea of mixed dos+unix aliases in one command line and many (CMD, Powershell) people found this combination interesting.
Very good if this people familiar with Lua API - to create usefull aliases that translate it to DOS equivalent.

As for me ConEmu (only 3Mb in archive) is more than enough. Bacause of i`m use MSysGit(MINGW32) Bash shell with included(compiled) UNIX commands. And i can create aliases in my bash_profile.

My idea was to extend MSYSGIT enviroment PATH from windows to control combination of pakage units from console.

**Comment by jakoch** [comment]
Ok, the integration is done.

ConEmu needs some additional tweaks of it's configuration.
The goal is to get a "good" out-of-the-box experience, when the Console is started from the SCP.

**Open Console Splitscreen from SCP**
The SCP executes `./bin/conemu/conemu.exe /config ConEmu.xml` to start ConEmu.
This will still trigger the FastConfiguration of ConEmu (= first time start).
The feature "Start into Splitscreen" from SCP is still missing, 
but `console.bat` will open a split screen with Windows Prompt (on top) and Git Bash (on bottom).

- [ ] adjust `ConEmu.xml`
  - [ ] reduce number of Tasks
  - [ ] fix the paths in Tasks to use the `\server\bin` dir
  - [ ] add task for `cmd | git bash` splitscreen
  - [ ] add ICO for Windows Prompt
