### ISSUE TITLE
Install Perl

### ISSUE THREAD

**Issue by motoringm** [WPN-XM/WPN-XM#372]
Hello,

I am working well with WPИ-XM Serverstack for Windows Version 0.6.0. 
Is there any way that I can install Perl as well along with this?

Thanks
M

**Comment by jakoch** [comment]
Hey M,

sure. You might install it manually: 
1. Download a version of Perl via http://wpn-xm.org/components.php or directly from the vendor
2. Extract to `c:\server\bin\perl`
3. Run `\bin\perl\relocation.pl.bat` and `\bin\perl\update_env.pl.bat`

Best, Jens

**Comment by motoringm** [comment]
Thanks.

I downloaded the strawberry-perl-5.20.2.1-64bit.zip file. Created a folder
c:\server\bin\perl
Then extracted  the zip file and copied the  contents to the above folder.
Stopped the WPN-XM server and quit
Double clicked the .bat files to execute - \bin\perl\relocation.pl.bat and
\bin\perl\update_env.pl.bat
Started the WPN-XM server

Created a sample .pl file


*Mahesh Murali* | Web Developer
e: mahesh.murali@motoring.co.uk
t: 0844 576 7444

Web <http://www.motoring.co.uk/> | Facebook
<http://www.facebook.com/motoringcouk> | Twitter
<http://twitter.com/motoringcouk>

On 17 April 2015 at 09:56, Jens A. Koch <notifications@github.com> wrote:

> Hey M,
>
> sure. You might install it manually:
> 1. Download a version of Perl via http://wpn-xm.org/components.php or
> directly from the vendor
> 2. Extract to c:\server\bin\perl
> 3. Run \bin\perl\relocation.pl.bat and \bin\perl\update_env.pl.bat
>
> Best, Jens
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPN-XM/WPN-XM/issues/372#issuecomment-93947093>.
>

-- 


---------------------------------------------------------

This e-mail together with any attachments is intended only for the use of the addressee and may contain information which is privileged and confidential. If the reader of this e-mail is not the intended recipient you are hereby notified that any use, dissemination, forwarding, printing or copying of this e-mail is strictly prohibited.

Addressees should check this email for viruses. motoring.co.uk Ltd makes no representations as regards the absence of viruses in this e-mail. If you have received this e-mail in error please notify our technical department immediately by e-mail at help@motoring.co.uk Please then immediately delete, erase or otherwise destroy this e-mail and any copies of it.

Any opinions expressed in this e-mail are those of the author and do not necessarily constitute the views of motoring.co.uk Ltd. Nothing in this e-mail shall enter motoring.co.uk Ltd in any contract or obligation.
motoring.co.uk Ltd is registered in England no. 6073777. Registered office: 8 St. John Street, Manchester, M3 4DU.

**Comment by motoringm** [comment]
Thanks.

I downloaded the strawberry-perl-5.20.2.1-64bit.zip file. Created a folder
c:\server\bin\perl
Then extracted  the zip file and copied the  contents to the above folder.
Stopped the WPN-XM server and quit
Double clicked the .bat files to execute - \bin\perl\relocation.pl.bat and
\bin\perl\update_env.pl.bat
Started the WPN-XM server

Created a sample .pl file and tried to run: http://locahost/test.pl. It did
niot run.

Please let me know where to configure the perl execution.

Thanks
M



*Mahesh Murali* | Web Developer
e: mahesh.murali@motoring.co.uk
t: 0844 576 7444

Web <http://www.motoring.co.uk/> | Facebook
<http://www.facebook.com/motoringcouk> | Twitter
<http://twitter.com/motoringcouk>

On 17 April 2015 at 10:21, Mahesh Murali <mahesh.murali@motoring.co.uk>
wrote:

> Thanks.
>
> I downloaded the strawberry-perl-5.20.2.1-64bit.zip file. Created a folder
> c:\server\bin\perl
> Then extracted  the zip file and copied the  contents to the above folder.
> Stopped the WPN-XM server and quit
> Double clicked the .bat files to execute - \bin\perl\relocation.pl.bat
>  and \bin\perl\update_env.pl.bat
> Started the WPN-XM server
>
> Created a sample .pl file
>
>
> *Mahesh Murali* | Web Developer
> e: mahesh.murali@motoring.co.uk
> t: 0844 576 7444
>
> Web <http://www.motoring.co.uk/> | Facebook
> <http://www.facebook.com/motoringcouk> | Twitter
> <http://twitter.com/motoringcouk>
>
> On 17 April 2015 at 09:56, Jens A. Koch <notifications@github.com> wrote:
>
>> Hey M,
>>
>> sure. You might install it manually:
>> 1. Download a version of Perl via http://wpn-xm.org/components.php or
>> directly from the vendor
>> 2. Extract to c:\server\bin\perl
>> 3. Run \bin\perl\relocation.pl.bat and \bin\perl\update_env.pl.bat
>>
>> Best, Jens
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/WPN-XM/WPN-XM/issues/372#issuecomment-93947093>.
>>
>
>

-- 


---------------------------------------------------------

This e-mail together with any attachments is intended only for the use of the addressee and may contain information which is privileged and confidential. If the reader of this e-mail is not the intended recipient you are hereby notified that any use, dissemination, forwarding, printing or copying of this e-mail is strictly prohibited.

Addressees should check this email for viruses. motoring.co.uk Ltd makes no representations as regards the absence of viruses in this e-mail. If you have received this e-mail in error please notify our technical department immediately by e-mail at help@motoring.co.uk Please then immediately delete, erase or otherwise destroy this e-mail and any copies of it.

Any opinions expressed in this e-mail are those of the author and do not necessarily constitute the views of motoring.co.uk Ltd. Nothing in this e-mail shall enter motoring.co.uk Ltd in any contract or obligation.
motoring.co.uk Ltd is registered in England no. 6073777. Registered office: 8 St. John Street, Manchester, M3 4DU.

**Comment by jakoch** [comment]
> Created a sample .pl file and tried to run: http://locahost/test.pl. It did not run.
> Please let me know where to configure the perl execution.

Hey M,

the Perl integration is not finished.
You might run Perl scripts with the installed Strawberry Perl, but this will not run in the web context.

The following two issues deal with the Perl integration:
- https://github.com/WPN-XM/WPN-XM/issues/125
- https://github.com/WPN-XM/WPN-XM/issues/209
As you can see, Peter tried to get this running in the web context.
But he couldn't get the fstcgi-wrapper script working and it was sufficient for him to work with Perl on the CLI. 

- I know that there is a module "dancer" which is often used to quick start web apps and as a development server. You might start a dancer app on a specific port and hide it behind nginx, via proxy forwarding. Simply install the module and try it out...
- The same principle should work for the PSGI server Starman and Thrall... i described this before, see:  https://github.com/WPN-XM/WPN-XM/issues/209#issuecomment-49087946
- ` plackup -s Thrall --port=9999 your-app.psgi` & nginx server block with dev domain forwarding to port 9999

Feel free to experiment and get this running....
Contributions in this area are very welcome.

Best, Jens

**Comment by jakoch** [comment]
Ok - maybe a Perl hacker will come and contribute.
I'm closing this for now.
