### ISSUE TITLE
Webinstaller 403 mariadb

### ISSUE THREAD

**Issue by Lartza** [WPN-XM/WPN-XM#373]
Installer fails to download mariadb.zip, HTTP error 403

WPNXM-0.8.2-Webinstaller-Setup-php56-w64.exe

**Comment by jakoch** [comment]
Thank you for reporting.
The upstream is gone: http://ftp.hosteurope.de/mirror/archive.mariadb.org/mariadb-10.1.4/win32-packages/mariadb-10.1.4-win32.zip
I need to switch the mirror...
