### ISSUE TITLE
Upgrade PHP in WPИ-XM  0.6.0

### ISSUE THREAD

**Issue by motoringm** [WPN-XM/WPN-XM#375]
Hi Team,

I am using WPИ-XM Serverstack for Windows Version 0.6.0 with PHP version 5.4.23
I am looking to upgrade PHP version to 5.6.

Could you please let me know the steps to do that?

Thanks
M

**Comment by jakoch** [comment]
Hey M,

1. go to http://wpn-xm.org/components.php
2. go to "PHP x86" - "latest version"
    - this is atm PHP v5.6.8
    - download http://windows.php.net/downloads/releases/php-5.6.8-nts-Win32-VC11-x86.zip
3. rename your PHP folder "c:\server\bin\php" to "c:\server\bin\php_5.4.23"
4. extract `php-5.6.8-nts-Win32-VC11-x86.zip` into a new folder `c:\server\bin\php`

Regards, Jens

**Comment by jakoch** [comment]
Ok, no further issue report -  i guess it worked. 
Closing the issue. Feel free to open a new ticket, if you have questions or run into problems.

**Comment by motoringm** [comment]
Was a bit busy fora couple of days. I just uninstalled the old WPN-XM and
installed a new full stack version.

Thanks

On Thursday, 23 April 2015, Jens A. Koch <notifications@github.com> wrote:

> Closed #375 <https://github.com/WPN-XM/WPN-XM/issues/375>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPN-XM/WPN-XM/issues/375#event-288614974>.
>


-- 
*Mahesh Murali* | Web Developer
e: mahesh.murali@motoring.co.uk
t: 0844 576 7444

Web <http://www.motoring.co.uk/> | Facebook
<http://www.facebook.com/motoringcouk> | Twitter
<http://twitter.com/motoringcouk>

-- 


---------------------------------------------------------

This e-mail together with any attachments is intended only for the use of the addressee and may contain information which is privileged and confidential. If the reader of this e-mail is not the intended recipient you are hereby notified that any use, dissemination, forwarding, printing or copying of this e-mail is strictly prohibited.

Addressees should check this email for viruses. motoring.co.uk Ltd makes no representations as regards the absence of viruses in this e-mail. If you have received this e-mail in error please notify our technical department immediately by e-mail at help@motoring.co.uk Please then immediately delete, erase or otherwise destroy this e-mail and any copies of it.

Any opinions expressed in this e-mail are those of the author and do not necessarily constitute the views of motoring.co.uk Ltd. Nothing in this e-mail shall enter motoring.co.uk Ltd in any contract or obligation.
motoring.co.uk Ltd is registered in England no. 6073777. Registered office: 8 St. John Street, Manchester, M3 4DU.

**Comment by jakoch** [comment]
Ah, ok!
New installation is always a good thing.

Short note: i released a new version of the Control Panel today:
fetch a boxed version from https://github.com/WPN-XM/server-control-panel/releases/tag/0.8.2
and unzip into the root folder of the stack.
