### ISSUE TITLE
Service indicators not changing to red/green and cannot stop services

### ISSUE THREAD

**Issue by nasl** [WPN-XM/WPN-XM#377]
I launch server panel, but depending on some conditions, maybe because of autostrating or smth - I cannot stop or the indicators of the service are showing wrong status - green when they are not running. When I press "Stop" - no change. "Start" - program crash. Starting service 1 by 1 - no change to indicators, but the service responds

I one sentence - it does not work right
latest 0.8.1+nnnn win64php55  release

**Comment by nasl** [comment]
now it seems I can start/stop php and nginx, but not memcached and mariadb

**Comment by jakoch** [comment]
Cross-posting this:

Here we go: https://github.com/WPN-XM/server-control-panel/releases/tag/0.8.2
- https://github.com/WPN-XM/server-control-panel/releases/download/0.8.2/wpnxm-scp-x86_64_boxed.zip
- https://github.com/WPN-XM/server-control-panel/releases/download/0.8.2/wpnxm-scp-x86_boxed.zip

I've tested this against a Lite Installer-v0.8.1-PHP55-x86 and i couldn't reproduce the crash.
Please give some feedback..

**Comment by jakoch** [comment]
I'm closing the issue, because there is no feedback.
I the issue is resolved by updating to the latest version of the Server Control Panel.
If the issue remains, feel free to post again. Thank you.

**Comment by nasl** [comment]
Sorry for no feedback, yes, most of the issues are solved with new control panel

**Comment by jakoch** [comment]
Thank you! 
If other problems pop up, keep me updated. 
Regards, Jens
