### ISSUE TITLE
mariadb - windows 8.1 start problem

### ISSUE THREAD

**Issue by house-md** [WPN-XM/WPN-XM#383]
Hello, Yesterday I installed this awesome package but i have a little problem. All services can be started from Server Controll Panel except mariaDB... its without error... If i started it from Task manager its running. I tried reinstall mysqld service, run Server Controll Panel as admin, I also disabled UAC... 

Thank you for reply and have a nice day.

**Comment by jakoch** [comment]
Hey Michael,
thank you for reporting this issue.
I will try to reproduce it on a Win8 box.

**Comment by house-md** [comment]
Thank you for reply, I'll try it this weekend. I used full installer with php 5.6 and x64.

**Comment by DDuarte** [comment]
Not sure why but I have the same issue.

I used `WPNXM-0.8.2-Webinstaller-Setup-php56-w64` on W8.1 and picked Base, WPN-XM Tray App and Webinterface. Either clicking All Daemons : Start or pressing the start of each service individually MariaDB refuses to start (Nginx and PHP are okay).

Starting MariaDB from the command line using `mysqld --console` starts it without issues.

**Comment by house-md** [comment]
Sorry i forgot to reply. The problem still persists and log file is empty...

**Comment by jakoch** [comment]
@DDuarte 
I've tested the  [WPNXM-0.8.2-Webinstaller-Setup-php56-w64.exe](https://github.com/WPN-XM/WPN-XM/releases/download/v0.8.2/WPNXM-0.8.2-Webinstaller-Setup-php56-w64.exe) on Windows 7 and installed the components: Base + Tray App + Webinterface.
Starting and stopping the daemons works for me.
I can not reproduce this issue.

I don't want to guess around, but it might be a 32bit/64bit configuration issue.
If this is the case, then MariaDb will report this in the error log or show it during a manual startup.
Please check the logs and config manually.

You are reporting that the log file is empty. 
If this is a configuration file issue, then it's possible that our custom log file location (`/server/logs/mariadb_error.log`) is not used, but the log files are created somewhere in the MariaDb folder instead. Would you be so nice to look for them?

**Comment by DDuarte** [comment]
Nothing is written and no logs are created when attempting to start MariaDB from the Server Control Panel.

When starting mysqld manually the file mariadb_error.log contains
```
150511  1:02:02 [Note] InnoDB: Using mutexes to ref count buffer pool pages
150511  1:02:02 [Note] InnoDB: The InnoDB memory heap is disabled
150511  1:02:02 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
150511  1:02:02 [Note] InnoDB: Memory barrier is not used
150511  1:02:02 [Note] InnoDB: Compressed tables use zlib 1.2.3
150511  1:02:02 [Note] InnoDB: Not using CPU crc32 instructions
150511  1:02:02 [Note] InnoDB: Initializing buffer pool, size = 128.0M
150511  1:02:02 [Note] InnoDB: Completed initialization of buffer pool
150511  1:02:02 [Note] InnoDB: Highest supported file format is Barracuda.
150511  1:02:02 [Note] InnoDB: Redo log crypto: unencrypted key ver.
150511  1:02:02 [Note] InnoDB: 128 rollback segment(s) are active.
150511  1:02:02 [Note] InnoDB: Waiting for purge to start
150511  1:02:03 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.22-72.0 started; log sequence number 1616697
150511  1:02:03 [Note] Plugin 'FEEDBACK' is disabled.
150511  1:02:03 [Note] Server socket created on IP: '::'.
150511  1:02:03 [Note] Event Scheduler: Loaded 0 events
150511  1:02:03 [Note] mysqld: ready for connections.
Version: '10.1.4-MariaDB'  socket: ''  port: 3306  mariadb.org binary distribution
```

After this I can use the manually started mysql server without issues.

**Comment by jakoch** [comment]
Thank you. 
One more test please: does MariaDb start, when using `start-wpnxm.bat`?

**Comment by DDuarte** [comment]
Indeed it does.

**Comment by jakoch** [comment]
Hmm. 

There is only one difference i can spot. The batch file uses the `--defaults-file=path\to\my.ini` directive to set the configuration file, while the SCP just executes `mysqld` and relies on automatical lookup. It might be that `mysqld` doesn't pick up the config file at all, when invoked from the SCP.

According to the docs (https://mariadb.com/kb/en/mariadb/configuring-mariadb-with-mycnf/#location-in-windows) the `my.ini` file can reside at `C:\`, `C:\Windows` and `INSTALLDIR`.
In our case `INSTALLDIR` is `server\bin\mariadb`. I wonder if this behavior was changed.

You could try to copy the `server\bin\mariadb\my.ini` file to `C:\` and try a start from the SCP.

Anyway, i will include the `--defaults-file` directive in the SCP (https://github.com/WPN-XM/server-control-panel/blob/master/src/servers.cpp#L460) to make sure the config file is picked up everytime.

A recompiled SCP is incoming. Estimated landing time of the new release: 1h.
Let's see how that turns out...

**Comment by DDuarte** [comment]
I found out what was causing the problem on my system, I guess it's an "user" fault:
I had an old MySQL install that created the MySQL service and when I uninstalled it did not remove the service entry. After running `sc delete "MySQL"` WPN-XM CP can start MariaDB.

@house-md: can you verify if this is what is happening in your system?

**Comment by jakoch** [comment]
Ah, ok - i'm glad you found out what caused the problem.

I think, to have the "defaults-file" directive in the SCP will not hurt and the build is already in progress.

As an idea: We could probably put together a "diagnose" script, checking the "user environment".
And one of these tests could be a check for "an old mysql service". 
We are far from that, but this would help a lot of users in the long run.

**Comment by house-md** [comment]
@DDuarte: I will try it maybe after 4-5 hours... Now I'm at work, but I think it could be solution...

**Comment by jakoch** [comment]
> P.S @jakoch In the commit you did I think you need \ instead of a single \ because of escape sequences :P

Yes - i messed up again. Shame on me.

**Comment by jakoch** [comment]
Can not reproduce. Without feedback, i'm stuck here.
Feel free to open a new ticket, if the issue remains...
