### ISSUE TITLE
progress bar ends with 103%

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#385]
The number of components is not in sync with the number of UpdateTotalProgress() calls.
For instance: imagick is one component in the "Component Selection" screen, but during the installation two calls are made to UpdateTotalProgress(). One time for the PHP extensions, one time for Imagick itself.

**Comment by klonos** [comment]
I had taken this screenshot a while ago, but somehow failed/forgotten to file an issue.

![wpn-xm_total_installation_progress_103percent](https://cloud.githubusercontent.com/assets/2423362/7474823/17783d04-f387-11e4-8f11-77695e72e64b.png)

**Comment by jakoch** [comment]
I've dropped the percentage display during component extraction in favor of a simple component counter. To get rounded percentages right is complicated, because one would have to switch from Integers to Extended in Pascal and then apply the "Largest Remainder Method" and sum the largest Fractions of the rounded percentages up to get close to 100. But there will always be a little round-off-error. If someone feels like getting the percentage fractions working, then i will happily accept the contribution.
