### ISSUE TITLE
404 Not Found for phpext_phalcon.zip

### ISSUE THREAD

**Issue by mindplay-dk** [WPN-XM/WPN-XM#390]
The installer fails with an error message - the dialog is pretty confusing:

![image](https://cloud.githubusercontent.com/assets/103348/7671059/2791a65a-fcbd-11e4-9619-f7a4e1dccebe.png)

"Click retry or cancel", but the only button in the dialog is an OK button. (I know, the retry and cancel buttons are in the *other* window, but that's pretty confusing.)

Anyhow, the installer doesn't let me skip this package - it just takes me around and around in a loop, so my only option is to cancel...

**Comment by jakoch** [comment]
Thank you for reporting the issues.

- [ ] fix registry and crawler for phpext_phalcon
The Phalcon guys changed the download URLs - and so our registry is out of sync.

- [ ] enable skipping of failed download on webinstallers

- [ ] adjust error message by redeclaring the language constants `{cm:IDP_RetryCancel} & {cm:IDP_RetryNext}`
The "confusing" message is part of "innosetup-download-plugin".
See https://github.com/WPN-XM/WPN-XM/blob/master/bin/innosetup-download-plugin/idp.iss#L652

**Comment by jakoch** [comment]
Ok, all things added.

Some notes on this:

- I rewrote the `get` script to address the "phpext_phalcon" issue. It was a problem with the array key. Phalcon is one of those extensions, where not only the "major.minor" version of PHP is important, but the "patch level" counts, too.
- The new message for `cm:IDP_RetryNext` `Click ''OK'' to close. Then click ''Retry'' to try downloading the file again. Click ''Next'' to skip this file and continue installing anyway. Please report this issue, if it's not a client-side connectivity problem.` I hope this is less confusing.
- The next release of the webinstallers will include the message and allow to skip a failed download.

**Comment by mindplay-dk** [comment]
awesome :+1:
