### ISSUE TITLE
Wordpress Permalinks

### ISSUE THREAD

**Issue by faoliveira** [WPN-XM/WPN-XM#393]
Hi,

I have wordpress installed in the path `C:\Dev\server\www\wordpress`. And in domains-enabled folder the [wordpress.conf](http://pastebin.com/1bT7RxRN) file. 

Back in  Host File Manager, I put the address 127.0.0.1 and in the name wordpress.dev. And restart the server.

1) wordpress.dev adress doesn't work. I mean, the browser just download a [download file](http://pastebin.com/1EyBbQw6) (?);
2) Permalinks in wordpress not also works.

And thanks for all

**Comment by jakoch** [comment]
Hey 

1. Download Wordpress - https://wordpress.org/latest.zip
2. Extract `/wordpress` folder from zip to `C:\server\www\`
3. Start Servers & Access `localhost/wordpress`
4. You will be redirected to `http://localhost/wordpress/wp-admin/setup-config.php`

5. add `127.0.0.1` and `wordpress.dev` to `hosts` file
6. add the following `wordpress.conf` to `server\bin\nginx\conf\domains-enabled` folder

```
server
{
    listen       127.0.0.1:80;
    root         www/wordpress;
    index        index.php;
    server_name  wordpress.dev;

    access_log   logs/wordpress.dev.access.log;
    error_log    logs/wordpress.dev.error.log;

    gzip_static on;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # add trailing slash to "*/wp-admin" requests to make the admin interface work
    rewrite /wp-admin$ $scheme://$host$uri/ permanent;

    # prevent access to any files starting with a dot, like .htaccess
    location ~ /\. { access_log off; log_not_found off; deny all; }

    # do not log access to robots.txt and favicon.ico
    location = /robots.txt { access_log off; log_not_found off; }
    location = /favicon.ico { access_log off; log_not_found off; }

    # deny access to some files
    location ~ /(\.|wp-config.php|readme.html|license.txt) { deny all; }

    # send "expires headers" and turn off "404 error logging".
    location ~* ^.+\.(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|rss|atom|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
        access_log off;
        log_not_found off;
        expires max;
    }

    # use fastcgi for all php files
    location ~ \.php$ {
        try_files      $uri =404;
        fastcgi_pass   127.0.0.1:9100;
        fastcgi_intercept_errors on;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param  PATH_INFO $document_uri;
        include        fastcgi_params;
    }
}
```

7. restart nginx
8. Now: when you browse to `http://wordpress.dev/` you will be redirected to a wrong URL `http://wordpress.dev/index.php/wp-admin/setup-config.php`. This one is already rewritten.
9. You need to remove the index.php part from it and use http://wordpress.dev/wp-admin/setup-config.php` to install Wordpress.
10. Follow install instructions...
11. Frontend: http://wordpress.dev/ & Backend: http://wordpress.dev/wp-admin/

Regards, Jens

**Comment by faoliveira** [comment]
Thanks for the support.  Well, did exactly what is above, the difference is WPN-XM installed in `C:\Dev\server\`

Neither wordpress.dev and permalinnk worked :/

acess.log: http://pastebin.com/wkvx3UbB
error.log: http://pastebin.com/meB2yebz

**Comment by jakoch** [comment]
> Thanks for the support.

Glad i could help.

Is the issue resolved? I couldn't find any http://wordpress.dev/ related entries in the logs.

**Comment by jakoch** [comment]
Feel free to post, if the issue is not resolved, yet.
