### ISSUE TITLE
Feature: opcache

### ISSUE THREAD

**Issue by mindplay-dk** [WPN-XM/WPN-XM#397]
Please consider including [opcache](http://php.net/opcache) - I realize this is considered a production feature by some, but it's often important for unit-testing and benchmarking to assess production performance.

**Comment by jakoch** [comment]
The opcache is included from PHP 5.5 on.
It's just a matter of enabling and tweaking it in the `php.ini` files.

- [ ] enable opcache and tweak settings a bit
  - https://github.com/WPN-XM/WPN-XM/blob/master/configs/php/php55.ini-dev
  - https://github.com/WPN-XM/WPN-XM/blob/master/configs/php/php56.ini-dev
