### ISSUE TITLE
error in update.php

### ISSUE THREAD

**Issue by soulraven** [WPN-XM/WPN-XM#404]
i get this error,
 Fatal error: Call to a member function getTimestamp() on boolean in C:\server\www\tools\webinterface\php\Helper\Updater.php on line 44

also are more other errors when installing using webinstaller, varnish, clousure, both archive are not founded when install trys ot installs the packages

**Comment by jakoch** [comment]
Hey!

Thanks for reporting the errors.

Sidenote: You are the first person setting the feature flag toggle to true, in order to unlock hidden and unfinished features. :+1:

**Updater**
The error results from the cross domain request (CORS) to the registry,
which is under Access-Control now, but wasn't back in the days: 
`Access-Control-Allow-Origin: https://render.githubusercontent.com`.
The Github guys changed the githubusercontent stuff quite a bit.
So i need to find new way to fetch the registry file again. Maybe via our server as proxy.

**Registry**
Yes, it might be out of sync.
I'm running a link check.

**Comment by soulraven** [comment]
i will be glad to test other feature, your app is great, but will be more nice if you can define new vhost on nginx server, or install new php modules directly from web interface.
also watch for a error when zeromq module is enable, need to have some libzmq.dll inside the main php folder.
and also a zeromq interface will be nice, or varhish, or memcache, or any other application installed, also the posibilty to start/stop from interface

**Comment by soulraven** [comment]
imagick same problem....imposibile to download

**Comment by jakoch** [comment]
> i will be glad to test other feature, your app is great

Thanks - i appreciate it.

> define new vhost on nginx server

It's a long standing feature request, see #2

>  install new php modules directly from web interface

This is a nice idea and it's easy to implement using Pickle.

I will set the other items, like adding ZMQ and Varnish to the interfaces, on the todo list.

I will need to fix some crawlers and get the registry back in sync first.

**This current Registry Status:**
![screencapture-localhost-updater-1434236791972](https://cloud.githubusercontent.com/assets/85608/8146311/05ffcb68-1232-11e5-9032-e452a41fa24b.png)

**Comment by jakoch** [comment]
- [x] Updater: fixed URL to registry and getting the Date header

**Comment by soulraven** [comment]
now all the changes are commited back to the webinstaller installer? because still get the same errors on instalation

**Comment by jakoch** [comment]
> now all the changes are commited back to the webinstaller installer?

No.

For the downloads:
All webinstallers use header forwarding to the real download URL. 
So, internally the webinstallers use the same download URLs as posted above.
It looks like this: https://github.com/WPN-XM/WPN-XM/blob/master/installers/webinstaller-php56-w32.iss#L294
This allow to "fix" download URLs in the registry, when the become outdated or invalid.

For the Webinterface change (Updater):
The webinterface is not downloaded by the webinstaller.
It's a packaged component.
This will ship with the next release of the webinstallers.

> because still get the same errors on instalation

Which webinstaller are you using?

**Comment by jakoch** [comment]
I hope the original issue is resolved.

> also watch for a error when zeromq module is enable, need to have some libzmq.dll inside the main php folder.
and also a zeromq interface will be nice, or varhish, or memcache, or any other application installed, also the posibilty to start/stop from interface

Indeed, that would be nice. Feel free to contribute.

**Comment by jakoch** [comment]
- [x] phpext_zeromq - misses libzmq.dll, #415
