### ISSUE TITLE
Wiped out all files under www including symlinks

### ISSUE THREAD

**Issue by TeroBlaZe** [WPN-XM/WPN-XM#427]
After uninstalling WPN-XM fucked up all my project files inside directory which was created as symbolic link to another directory on different drive. This is not a major problem to me of course I had a backup and I have no any claims to WPN-XM, but anyway it might be important for others. So please if it possible leave a user directories or at least do not to do a recursive removing of user directories under www directory. It was very odd to see my project directory clean as a whistle.

**Comment by jakoch** [comment]
Hey TeroBlaZe,

man that's odd! I'm really sorry for the mess created by the uninstaller.

This need an immediate fix.

I guess i will have to switch to the [DelTree()](http://www.jrsoftware.org/ishelp/index.php?topic=isxfunc_deltree) function then. It will remove directories that are reparse points, but it will not recursively delete files/directories inside them.
