### ISSUE TITLE
WPN-XM.exe service won't start.

### ISSUE THREAD

**Issue by Khashul** [WPN-XM/WPN-XM#432]
Hi,

I'm trying to set WPN-XM to run as a service on a virtual box so I don't need to stay logged in. I am able to run WPN-XM by running the wpn-xm.exe but as a service it errors with "Error 1053: The service did not respond to the start or control request in a timely fashion".

<code> sc create wpnxm binPath= "D:\wpn-xm\wpn-xm.exe" DisplayName= "WPN-XM Server Stack" start= auto</code>

I've tested this on Windows Server and Windows 7 and out of the box once the service is created it doesn't start.

**Comment by jakoch** [comment]
Hey Khashul,

i've not expected that someone tries to use the `wpn-xm.exe` itself as a service.
Its a dual application, which has a console and a GUI mode, but its not prepared to run as a service itself. 

I understand the general feature request: to run the servers as services.
At the moment WPN-XM does not support Services. 
It is still an open issue: #165
Feel free to contribute....

Here are some suggestions: 
Firstly, you might try to use the Server Control Panel and 
enable "Start WPN-XM SCP, when Windows starts?" and then
select the desired servers to start in the section "Start these daemons, when starting SCP?".
This will place WPN-XM into the autostart section and when it starts, it will start the selected daemons.

Secondly, you can run a program when no one is logged in, by using the Windows Task Scheduler.
Look for a thingy called "On Startup Trigger" (maybe under Advanced config of a new task).

Thirdly, you may try NSSM or another service-installation helper to set the servers up as services.

Please keep me updated, on how you solved it.

Regards, Jens

**Comment by Khashul** [comment]
Hi Jens,

Unfortunately I have not been able to get this working. I've been trying on and off for sometime. It's not helped by the fact I am unable to restart the VM as it's running other critical services. For now I'll have to wait till #165 is complete.

Thanks for all your help.
