### ISSUE TITLE
Fatal error: Cannot redeclare class Webinterface

### ISSUE THREAD

**Issue by HRoger** [WPN-XM/WPN-XM#433]
Hi there,

 I got the following error every time I start the webinterface for the first time after installation:
Fatal error: Cannot redeclare class Webinterface\Helper\Projects in C:\server\www\tools\webinterface\php\Helper\Projects.php on line 14.

I think you could solve this error by change the following:

On tools/webinterface/index.php line 20

Instead if (is_file($helper)) { include $helper; } 

should be 

if (is_file($helper)) { include_once($helper); }

Thanks

**Comment by jakoch** [comment]
Hey Herley, 

thank you for reporting the issue. 
Yes, your fix is right, the helper include messes with the autoloading.
Its bugfixed: https://github.com/WPN-XM/WPN-XM/issues/428

If you encounter more issues, please keep me updated...
Regards, Jens

**Comment by HRoger** [comment]
You are welcome. Thank you very much for your great work!
