### ISSUE TITLE
xdebug and opcache not working. Fixed

### ISSUE THREAD

**Issue by HRoger** [WPN-XM/WPN-XM#434]
After installing the full package installer 0.8.4 some php extensions where not installed on folder php/ext.
With Webinstaller  0.8.4 the extensions were downloaded properly but couldn't get xdebug and opcache to work. 

I found the following error on php.ini on line 2012
instead of:
zend_extension=php_opcache.dll

Should be:
zend_extension=C:/server/bin/php/ext/php_opcache.dll

and should add the following line in order to have xdebug working:

line 2013 should add:
zend_extension=C:/server/bin/php/ext/php_xdebug.dll

Hope it helps someone

**Comment by jakoch** [comment]
Ok, lets fix this...

- [ ] PHP Extensions not extracted
    - download and extraction works in Webinstaller 
    - extraction fails in Full/Standard installer
- [ ] xdebug not properly configured in php.ini
- [ ] opcache not properly configured in php.ini
