### ISSUE TITLE
memcache.dll, php_memcache.pdb and php_xdebug not unpackaged

### ISSUE THREAD

**Issue by HRoger** [WPN-XM/WPN-XM#438]
Hi there,

wpn-xm 0.8.5

memcache.dll, php_memcache.pdb and php_xdebug were not unpackaged.

I had to install it manually in order to start memcache and xdebug.

Thanks

**Comment by jakoch** [comment]
Ok, confirmed bug. 
The PHP extensions are not extracted.

**Comment by jakoch** [comment]
Fixed.
