### ISSUE TITLE
[webinterface] make mobile friendly.

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#448]
Same as #446 but for the web UI.

**Comment by jakoch** [comment]
I consider using the webinterface with a mobile device a rare use-case, because most users will stick to a desktop system for development.

If someone works on making the webinterface more mobile friendly, then i will happily accept a patch. 
Contributions welcome...

**Comment by jakoch** [comment]
Reopening.
Blocked, by "theme support" in the webinterface.

**Comment by jakoch** [comment]
I've updated the webinterface and changed more elements to Bootstrap.
I hope this improves the mobile usability, too.
