### ISSUE TITLE
[webinterface] No PHP version shown in Configuration -> PHP

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#451]
![wpn-xm-no_php_version](https://cloud.githubusercontent.com/assets/2423362/8997289/fee2d8b0-3762-11e5-95a4-97e0f3b98055.png)

**Comment by jakoch** [comment]
Seems the webinterface slowly falls apart. :(
It might be, that the "php" folder(s) in "bin" are not correctly named and the display is messed up.
Anyway, this should not happen.
