### ISSUE TITLE
No icon in wpn-xm.exe - need to manually add from unins000.exe

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#452]
Since 0.8.4 (not sure - perhaps 0.8.3) the SCP exe has no icon, so one has to manually add it to the desktop and quick launch bar shortcuts from unins000.exe that still has the icon.

**Comment by jakoch** [comment]
Ok, i guess i introduced this bug with this (https://github.com/WPN-XM/server-control-panel/commit/8af74b3a05f8cd8eedc1eedddec7a11a30e4b3ab). I will revert it and trigger a new build.

**Comment by jakoch** [comment]
Please give this build a try: https://github.com/WPN-XM/server-control-panel/releases/tag/0.8.5
