### ISSUE TITLE
[webinterface] Add a new section for the management of Zend Extensions.

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#453]
![wpn-xm-php_opcache_disabled](https://cloud.githubusercontent.com/assets/2423362/9035539/2c720aec-3a1c-11e5-87fe-dcbf58ee0cae.png)

**Comment by jakoch** [comment]
It's disabled, because its not a PHP Extension, but a Zend Extension, like Xdebug.
These need some more adjustments in `php.ini`. 

Feel free to add a section for the management of Zend Extensions.

**Comment by jakoch** [comment]
Implemented. https://github.com/WPN-XM/webinterface/pull/19
