### ISSUE TITLE
MariaDB not working after Upgrade Windows 10

### ISSUE THREAD

**Issue by semplon** [WPN-XM/WPN-XM#456]
Hello, I got problem running mariadb after I upgrade my windows version to windows 10. 
Every time i run mariadb, in few seconds it stopped without warning. even no error log recorded. 

Thanks,

**Comment by jakoch** [comment]
Hello Puguh, 

i can not reproduce this error. I've tested MariaDb v10.1.3 on Windows 10 and it works.

![mysql-windows10](https://cloud.githubusercontent.com/assets/85608/9110533/c4ae008a-3c3e-11e5-83a3-4b80dd9b354d.png)

**Comment by semplon** [comment]
thanks, it's work now after i upgrade wpn-xm to the latest version.

**Comment by jakoch** [comment]
Glad you solved it.

Sidenote: the latest version has some extraction issues with Imagick and PHP extensions.
A new release comes in the next few days.

Regards, Jens
