### ISSUE TITLE
Rewrite doesn't work

### ISSUE THREAD

**Issue by joannesalfa** [WPN-XM/WPN-XM#457]
I'm trying to test how it works.

I've created a new folder named "buddy" in www directory, then I went to edit C:\server\bin\nginx\conf\nginx.conf

I added a server block:

location localhost/buddy {
  rewrite /my-exact-file.html http://external-website.com/;
}

Restarted nginx service and I entered with URL localhost/buddy, it doesn't do anything.

**Comment by joannesalfa** [comment]
Nevermind I just made a mistake, it was /buddy , not localhost/buddy

**Comment by jakoch** [comment]
Glad you figured it out.

You might find some examples in the config folder: https://github.com/WPN-XM/WPN-XM/tree/master/configs/nginx/conf/domains-disabled
