### ISSUE TITLE
The Nginx is only single process...

### ISSUE THREAD

**Issue by kmvan** [WPN-XM/WPN-XM#458]
I write a comet PHP app, when a request is loading, nginx will block others request in a time.
I use apache instead nginx that all OK.
It's some settings error for my nginx?

**Comment by jakoch** [comment]
Hello Km.Van,

when you look at the process viewer, you will find several Nginx processes.
One of the processes is the master process and the other ones are the worker process.

Normally, when a new request comes in the master process will delegate to one of the workers.

On Windows there are limitations (see http://nginx.org/en/docs/windows.html):
- Although several workers can be started, only one of them actually does any work.
- Using multiple worker threads inside a single worker process.

You might try an alternative build of Nginx for Windows.
For instance, the builds from http://nginx-win.ecsds.eu/ have multi worker support.
http://nginx-win.ecsds.eu/download/nginx%201.9.3.1%20Lizard.zip

Please give me feedback, if replacing Nginx with this build solves the issue.

Best, Jens

**Comment by kmvan** [comment]
Thank you for reply, jakoch.

I am sorry that I can not provide useful feedback to you.

I am try upgrade NGINX to 1.9.3.1(multi process), and add some multi process settings(e.g. multi_accept), it works but still only single process XD.

Now I have not idea what shall I do...

**Comment by jakoch** [comment]
Maybe asking the question over at http://forum.nginx.org/ helps.
