### ISSUE TITLE
You need to stop hijacking "localhost" while WPN-XM is not running

### ISSUE THREAD

**Issue by joannesalfa** [WPN-XM/WPN-XM#459]
For some reasons, I switched WPN-XM to WAMPserver due to usage of Apache, I hadn't time to configure nginx for many reasons like php api url gives me download file which is wrong.

I disabled all daemons in WPN-XM, and started running wampserver, i tried to enter "localhost" and it shows WPN-XM redirection page, I was like WTF! I checked all daemons from WPN-XM are not running.

Should I uninstall WPN-XM to fix this issue?

**Comment by joannesalfa** [comment]
Related to https://github.com/WPN-XM/WPN-XM/issues/177

**Comment by joannesalfa** [comment]
I didn't install portable mode, It seems this #177 explains that I should manually remove server folder, correct?

**Comment by jakoch** [comment]
Stop the daemons. 
Check that they are down by using `wpnxm-status.bat` or `status.bat` depending on your version.
And don't forget to clear your browser cache... :)

**Comment by joannesalfa** [comment]
Woah, clearing my browser cache fixed my issue, I was worried so much!

Thanks!

**Comment by jakoch** [comment]
You are welcome!
