### ISSUE TITLE
Enable spdy with Web Install

### ISSUE THREAD

**Issue by lunak86** [WPN-XM/WPN-XM#464]
Hello,

I have downloaded nginx, mariadb and pho via webinstall.

Now I tried to configure the SSL server, but I am receiving:

"the "spdy" parameter requires ngx_http_spdy_module"

error message in nginx error log. Hiw to enable spdy, please?

Thanks a lot.

**Comment by jakoch** [comment]
The official Nginx build does not suppor SPDY, yet. You can't enable it.

**Comment by jakoch** [comment]
I've removed the "spdy" parameter from the config to avoid that people fall into the configuration trap.
