### ISSUE TITLE
services don't start if there is a space in the name of the containing folder

### ISSUE THREAD

**Issue by antoroxico** [WPN-XM/WPN-XM#465]
Please forgive my English (not my native language ) .

version: WPNXM-0.8.6-Standard-Setup-php56-w64 ( portable mode)
win 7 x64

I've run into a bug where services do not start if the folder that contains them has a space in the name

the server is stored in "E:\DATA\Software Development\server" when trying to start from the control panel , the green light flashes and nothing happens after that (no entry in any log file or propmt msg).

When reinstall the server in "E:\DATA\Software_Development\server" everything works perfectly .

running start.bat :

```
E:\DATA\Software Development\server>start.bat
Removing Temporary Files...
Creating Directories for Temporary Files...
Starting PHP FastCGI...
"E:\DATA\Software" is not recognized as an internal or external command,
program or batch file .

Starting MariaDb...
"E:\DATA\Software" is not recognized as an internal or external command,
program or batch file .

Starting Memcached...
"E:\DATA\Software" is not recognized as an internal or external command,
program or batch file .

Starting nginx...
"E:\DATA\Software" is not recognized as an internal or external command,
program or batch file .

Opening localhost in Browser...
```

**Comment by jakoch** [comment]
Thank you for reporting this issue.

I could change the installer to ensure that the installation path does not contain any spaces (#431) or
wrap the start commands in quotes.
