### ISSUE TITLE
webinstaller-php56-w32/64 build error

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#470]
Travis Log:
```
Compiling [Code] section
Error on line 1213 in Z:\home\travis\build\WPN-XM\WPN-XM\_build\webinstaller-php56-w32.iss: 
Column 26:Unknown identifier 'Filename_phpext_mailparse'
Compile aborted.
```

- [ ] fix compilation error

**Comment by jakoch** [comment]
The PHP extension Mailparse is not available for PHP 5.6 and up.
https://pecl.php.net/package/mailparse/2.1.6/windows

Commenting out...

**Comment by klonos** [comment]
Replacement (php >=5.4.0): https://packagist.org/packages/mmucklo/email-parse

**Comment by jakoch** [comment]
The extension is not well maintained and there is no other, we could replace it with.
We can't replace an extension with a package on the server stack level.
Using a Composer package on a per-project basis is always possible.

**Comment by klonos** [comment]
Fair enough. Was just a suggestion.
