### ISSUE TITLE
[nginx+node] provide node example app with nginx server block

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#484]
I received the following question on Facebook:

> How to create virtual host, on nodejs system as language server service ?
- [x] create NodeJS app exposing an access point at desired port (`localhost:5000`)
  - [ ] test direct access
- [x] create Nginx `server` block 
  - [x] `listen localhost:5000;` 
  - [x] `server_name nodeapp.dev`
    - [ ] test `nodeapp.dev`
  - [ ] add entry to hosts file
- [ ] add files to stack

---

Node

```
var http = require('http');

http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(5000, '127.0.0.1');

console.log('Server running at http://127.0.0.1:5000/');
```

Nginx

```
server {
  listen       127.0.0.1:5000;
  server_name  nodeapp.dev;

  root    www/nodeapp/public_html;
  index  index.html;

  log_not_found off;
  charset utf-8;

  location / {
    if (!-e $request_filename) {
      proxy_pass http://localhost:5000;
    }
  }
}
```
##

**Comment by xicond** [comment]
I need this run as services app and called daemon on linux, this done in Winginx, but Winginx not updatable
maybe need more friendly method to do this by UX

**Comment by jakoch** [comment]
You want to run the Node Application as a service?

You might use either `nssm`or `winsw` for to create a service.
There is also a npm module called `node-windows`.
You find it over here: https://github.com/coreybutler/node-windows
This tool uses `winsw` internally, it writes the XML config and registers the service, so its a bit less work.
You simply wrap your original Application into the `node-windows` service layer.

```
var Service = require('node-windows').Service;

// Create a new service object
var svc = new Service({
  name:'Hello World',
  description: 'The nodejs.org example web server.',
  script: 'C:\\server\\www\\nodeapp\helloworld.js'
});

// Listen for the "install" event, which indicates the
// process is available as a service.
svc.on('install',function(){
  svc.start();
});

svc.install();
```

Does this answer your question?

**Comment by jakoch** [comment]
Feedback please?

**Comment by jakoch** [comment]
> I need this run the nodejs app as services server and called daemon on linux, this done in Winginx, but Winginx not updatable

If you need this, then contribute..
