### ISSUE TITLE
[composer] disable xdebug on composer runs

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#487]
- [ ] diable xdebug temporary for Composer runs to avoid slow downs

Notes:
   - zend_extensions can not be disabled from the CLI, when invoking php.exe
   - its also not possible to override this value by a .user.ini
   - we need to modify the php.ini or provide a standalone php.ini for composer runs
   - [ ] lets go with modify: disable xdebug (if it is on) in php.ini before running Composer and return to the state it was before the Composer run
      - [ ] save old state
      - [ ] turn off
      - [ ] return to old state

**Comment by jakoch** [comment]
`composer.bat` uses the following call:
`%~dp0..\php\php.exe -c php.ini-composer %~dp0composer.phar --working-dir=%cd% %*`

Its a dead simple one liner with the following intentions behind it:
- when the composer.bat file is executed, we are in "\bin\composer"
- then php is called in the "\bin\php" folder. 
   - that allows to switch PHP versions by renaming a versionized PHP folder to just "PHP".
- with a custom php.ini for composer runs. 
    - the custom ini is needed to disable xdebug
    - and disabling xdebug is needed for performance reasons during the composer run
- php executes the composer.phar
- but we set the working dir for composer to the invocation path of the batch file
   - which is the project folder, were you call composer.bat

**Comment by blades-4ty** [comment]
May you please give a more detailed, step-by-step explanation on disabling xdebug while running composer? Thus, you will achieve what many other "secret clan" coders aren't able to. I don't know for what reason I couldn't find any thorough, simple, follow-along instruction on completing this task. Not all programmers know all the minor steps, yet. Thanks.

**Comment by jakoch** [comment]
> May you please give a more detailed, step-by-step explanation on disabling xdebug while running composer?

Yes, sure! But here i can only repeat myself to answer your question.

- Please let me cite my answer from StackOverflow: http://stackoverflow.com/a/33928053/1163786

    > My suggestion is to write a little invocation helper for running Composer.
> 
> The helper is a bash or batch script calling PHP with a custom php.ini, especially configured for Composer. Lets call it: php.ini-composer.
> 
> You could copy your current php.ini and adjust it for the Composer run, by removing xdebug or commenting it out, like so: ;zend_extension = "/path/to/my/xdebug.so".
> 
> While you are at it: setting memory_limit=-1 is helpful, too.
> 
> The full command looks like so on Windows: php.exe -c php.ini-composer composer.phar %*

- Then read the step-by-step explanation of what the command does from my post above (https://github.com/WPN-XM/WPN-XM/issues/487#issuecomment-157451028). 

- I've also provided an implementation (see the commits). You don't even need follow-along instructions. You just need to copy the relevant files (custom php ini and composer.bat).

I hope you get it done. Feel free to ask, if you need additional support.

Best, Jens
