### ISSUE TITLE
[Question] Update core components

### ISSUE THREAD

**Issue by lunak86** [WPN-XM/WPN-XM#490]
Hello,

how can I update core components (ngonx, mariadb, php) without complete uninstall, please? 

Thanks!

**Comment by jakoch** [comment]
Hey!

You can update the components manually.
The following steps should work:

1. Download the latest version for a component 
     - You find the latest versions for the components over at http://wpn-xm.org/components.php
2. rename the existing component folder inside `server\bin` to `component-old`
3. install the new version
4. copy configuration and data files from "component-old" to "component" folder

(If something goes wrong, you can still revert to the backup folder "component-old".
Simply delete the "component" folder and rename "component-old" to "component".)

Feel free to post all issues you encounter, while trying to update a component manually.

**Comment by lunak86** [comment]
Yes, excellent! Thanks a lot!
