### ISSUE TITLE
Very slow download from Github-Amazon AWs

### ISSUE THREAD

**Issue by dqlopez** [WPN-XM/WPN-XM#492]
Is it just me or everyone experiencing the same that all the download links in the site is painfully slow? You should provide mirrors for this instance.
##

**Comment by jakoch** [comment]
Hey Dante,

i'm sorry for the slow download speed, but for now the releases rely only on Githubs CDN.
I ditched uploading to SourceForge a while ago.

There was a user request for a mirror system before over at the mailing list.
I like the idea, but its not possible before issue #126 (installers need to be code-signed) is solved.

After that i could imagine to offer other download sources.
Maybe a simply rsync based mirror system or evan a torrent based distribution. 

I'm open for suggestions in regard to cloud storage provides.
Firstly, it would be nice, if the service is  free, as i don't want to run into high costs for storage or bandwidth and secondly, it must be possible to automate the upload.
Maybe Mega or pCloud cloud fit.
If you know a good service, please keep me updated.

Regards, Jens

**Comment by klonos** [comment]
> ...or evan a torrent based distribution

:+1:

**Comment by jakoch** [comment]
Ok, got a new suggestion for distribution: https://bintray.com/ - which is free for OSS.

**Comment by jakoch** [comment]
Ok, i did some more research on tools for mirroring and CDN'ing.

The most important projects are **MirrorBrain** and **MirrorBits**:
  - http://mirrorbrain.org/ (Apache, PostgreSQL, mod_asn on server; rsync/http/ftp on client)
  - https://github.com/etix/mirrorbits (written in Go; behind VLC and XMBC/Kodi.tv)
    - Mirrorlist: http://mirrors.kodi.tv/addons/isengard/addons.xml?mirrorlist

**Questions / Research**:
- Github Releases
  - is it possible to use Github Releases as the origin for the first mirror?
  - do i have to copy from Github Releases to server and then start mirroring?
  - is it possible to use Github Releases as the fallback source?
- Torrent Support?
- What about alternative download hosts like Bintray (Dropbox/Owncloud)?
  - Is it possible to use them as a mirror / can they be part of the mirror-list?
 
Requirements:
- automatic filesize and hash checks on mirrored files
- automatic disabling of mirror URLs with broken/invalid downloads
