### ISSUE TITLE
bind 127.0.0.1:80 failed

### ISSUE THREAD

**Issue by dqlopez** [WPN-XM/WPN-XM#493]
I am encountering this issue in Windows 10 when port is set to 80, the default.

`bind() to 127.0.0.1:80 failed (10013: An attempt was made to access a socket in a way forbidden by its access permissions)`

However, changing to any port other than 80 works as charm (8080 in my case). What seems to be causing this issue? I encountered this also when I tried the [nginx for Windows](http://nginx.org/en/docs/windows.html), that's why I tried WPN-XM thinking I wouldn't encounter this.

**Comment by jakoch** [comment]
There is some other service listening on port 80 on your system - its blocking the port.

You might use CurrPorts to find out: 
- http://www.nirsoft.net/utils/cports.zip or http://www.nirsoft.net/utils/cports-x64.zip

**Comment by dqlopez** [comment]
I tried cports as you suggested and sees that the only port 80 relevant here is this:

>System	4	TCP	80	http	0.0.0.0			0.0.0.0		Listening
>System					N/A				10/18/2015 9:28:38 AM
>System	4	TCP	80	http	::			::		Listening	System
>N/A				10/18/2015 9:28:38 AM

**Comment by jakoch** [comment]
If the port is used by "System PID 4", then the service "WWW-Publishingservice" (w3svc) or "Web Deployment Agent Service" might be using the port and you might disable it by using the services.msc control panel.

**Comment by dqlopez** [comment]
Thanks @jakoch for the lead information. I disabled **World Wide Web Publishing** service and this resolves the issue.

**Comment by jakoch** [comment]
:+1: Glad you solved it 

If you run into other issues with the stack, feel free to post them. 

Regards, Jens
