### ISSUE TITLE
[component] offline documentation browser

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#494]
I would like to add an offline documentation browser.
There are some nice tools out there, like Zeal, Velocity or DevDocs.
But i'm not sure, yet, which one to pick. 
What's your opinion? Do you know alternatives?

Note: it would be nice, if we could shrink the package size by selecting PHP specific documentation sets. It doesn't make sense to ship Unity3D or Haskell docu for a PHP stack.
- Zeal
  - https://zealdocs.org/ - https://github.com/zealdocs/zeal
  - 38 MB - https://bintray.com/artifact/download/zealdocs/releases/zeal-0.1.1-windows-x86.msi
- Velocity
  - https://velocity.silverlakesoftware.com/
  - 40 MB - https://velocity.blob.core.windows.net/downloads/VelocitySetup-1.0.6.msi
- http://devdocs.io/ - seems the offline version stores its data in the browser storage :(

---

- [x] pick one
- [x] add crawler
- [x] add download filename
- [x] add to registry
- [ ] add to installers 
  - only to full & standard
  - but not to lite & liteRC, because this will add 40 to 50MB to the installer size
##

**Comment by klonos** [comment]
> What's your opinion? Do you know alternatives?

Well, we should support OSS as much as possible. I cannot tell any differences functionality-wise between Zeal and Velocity and I like it when software has its code up in GitHub where people can contribute easily (bug reporting, feature requests, patches). So I say lets go with the first.

**Comment by jakoch** [comment]
I'm of the same opinion.

I didn't expect that "Zeal" as an "offline" documentation browsers ships without docsets.
The 38 MB are "only" Qt dependencies. One would have to install Zeal and then fetch some "docsets" first to get it into a ready-for-offline-usage mode.
In other words: this will only work out, if repackage Zeal with some docsets included.

**Comment by jakoch** [comment]
- [x]: added to registry: https://github.com/WPN-XM/registry/commit/89fdf39196118636633c65196124f614e7bfeb48

**Comment by jakoch** [comment]
won't add to installers. 
- no request 
- not possible to package docsets easily, blocked by https://github.com/zealdocs/zeal/issues/ 509

closing
