### ISSUE TITLE
[website] remove the listing of PHP 5.4 extensions from components page

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#497]
PHP 5.4 is EOL - http://php.net/supported-versions.php

**Comment by klonos** [comment]
Better to monitor usage stats and do this once the usage is low(er):

http://w3techs.com/technologies/details/pl-php/5/all

It seems that about 1/3 of the internet is still using 5.3 and another 1/3 using 5.4 while 5.5 is ~13%. I say wait perhaps till the percentages are flipped to 5.5 ~30% and 5.4 ~10%.

**Comment by jakoch** [comment]
The usage of unsupported branches is way too high on production environments.
The stats of 5.2 and 5.3 really scare me. These versions fade so slowly because of "oldstable" releases of the major linux distributions and their long-term support.

When you look at the stats posted in Jordi's blogs evaluating the Composer/Packagist requests,
you'll see a different PHP version adoption: http://seld.be/notes/my-view-of-php-version-adoption 
I guess, the post will get an update during the next month. These stats reflect the PHP version adoption of development boxes a bit better. 

Anyway..i stopped building installers for 5.4 with v0.8.3 intentionally during the security fixes only phase. Mainly because 7 was knocking on the door and my own resources of maintaing things are limited. Maintaining 4 PHP versions with multiple installers without any contributions in the form of commits is not working out. While working on open issues and giving support, i can only support two main versions and the bleeding edge at maximum.

The extension versions listed on the components page should fit the available release versions. 
I will remove the 5.4 display from the PHP Extensions section of the components page in order to make room for the upcoming 7.0 stuff. 
But i could add a supported / unsupported version message with some additional links pointing to the official download archives over at PHP.net and PECL.php.net.
The "old" links remain in the WPN-XM registry to support the old webinstallers, which retrieve the downloads via the API.

**Comment by klonos** [comment]
> ...and my own resources of maintaing things are limited.

Fair enough of course.

I am all for using updated/latest versions where and when possible. I just wanted to point the fact that some people still develop with previous versions because say of hosting provider versions not being updated. That's all.
