### ISSUE TITLE
[xdebug] add/enable for PHP 7 installers

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#508]
The Zend Extensions Xdebug is now available for PHP 7 - http://xdebug.org/updates.php#x_2_4_0beta1

Windows binaries will be added in **2.4.0beta2**, which is the next release of Xdebug.

- [x] re-add xdebug into PHP 7 installation wizards
  - [x] update crawler to fetch RC version - https://github.com/WPN-XM/updater/commit/6f58ab5a120530e74b0f0585b0448c27d9d627cd
 - https://github.com/WPN-XM/registry/blob/e1e97bd5b2c57008b70f3b2ed1c7dc5ebbea754a/literc-next-php7.0-w64.json
 - https://github.com/WPN-XM/registry/blob/e1e97bd5b2c57008b70f3b2ed1c7dc5ebbea754a/literc-next-php7.0-w32.json

**Comment by mindplay-dk** [comment]
xdebug 2.4 stable was released on March 3, any chance of an updated release soon?

I keep running into [this bug](https://bugs.xdebug.org/view.php?id=1241), as do [others](https://github.com/sebastianbergmann/php-code-coverage/issues/414) - this bug incorrectly reports lower code coverage percentage with e.g. `php-code-coverage`, which makes it difficult to run tests locally...

**Comment by jakoch** [comment]
Hey Rasmus!

That's odd. For now, the fastest way to solve the problem is to fetch and update the components manually. The links for the latest versions are:
- http://wpn-xm.org/get.php?s=php&v=7.0.5
- http://wpn-xm.org/get.php?s=phpext_xdebug&p=7.0

I'm sorry to disappoint you, but the chances for a new release "soon" are very low.
I have to apologize for the long development time, but i want to ship the Updater with the next release. Unfortunately, this means that there is still a lot work ahead. I guess, its about time to switch into full-time mode and invest some more money on the project to get the important stuff done.

Best, Jens

**Comment by mindplay-dk** [comment]
Maybe you should propose a 1.0 roadmap and create a kickstarter campaign? A lot of Windows developers rely on this package in their daily work. I'd donate ;-)

**Comment by timomayer** [comment]
i am really looking forward for a new release too. there were many changes in the last month (php7, nginx 1.10 stable, ...) so i think a new release makes a lot of sense. hope you find the time to do it would be awesome :)

**Comment by jakoch** [comment]
> a new release makes a lot of sense

Imminent! As soon as I can get the issues of v0.8.7 done. (I will drop some features from the Updater todo list to speed things up. So, it will only be a Downloader.) I'm hoping by the end of this month, but that depends on how quickly I can solve the outstanding issues. I want it out as much as anyone else does, trust me on that.

**Comment by jakoch** [comment]
>  I'm hoping by the end of this month

damn, times passes by so quickly. now there is 7.1 out.

> Maybe you should propose a 1.0 roadmap and create a kickstarter campaign? A lot of Windows developers rely on this package in their daily work. I'd donate ;-)

@mindplay-dk The real question is what holds people back from contributing to the project?
