### ISSUE TITLE
[website] fix changelog links on download page

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#511]
The changelog links are broken on the downloads page are broken.

- [ ] fix the links
- [ ] add the matching anchor for linking directly to the changelog of the released version
    - the base url is `https://github.com/WPN-XM/WPN-XM/blob/master/CHANGELOG.md`
    - the hash/anchor looks like `#v085---2015-07-12`
      -  version number without dots
      - `---` means space, minus/hyphen, space
      - date is `Y-m-d`      
    - example: https://github.com/WPN-XM/WPN-XM/blob/master/CHANGELOG.md#v085---2015-07-12

**Comment by klonos** [comment]
> ...- version number without dots

What will happen once you hit two-digit major versions (12.y.z for example) that perhaps need to have two-digit minor/bug versions too (12.12.1 or 12.1.12 or 12.12.12 for example)?

**Comment by jakoch** [comment]
Hmm...given the fact that i need over 90 days for a simple patch level version raise,
i will be gray an old when the project hits two-digit version numbers. :grinning: 

What will happen? The construction of the version number part will not change, when we go up in versions. But your concern is, that the version number (major.minor.patch) without dots could clash, right? E.g.

```
12.12.1 -> 12121
12.1.21 -> 12121
```

Thats actually one of the reasons why Asciidoc is better than Markdown (Not sure if it is a spec or implementation problem). 
with Adoc the escaping and stripping of chars was solved by replacing the dot with an underscore:
```
12.12.1 -> 12_12_1
12.1.21 -> 12_1_21
```
One can have version numbers as standalone, anchored headlines in Asciidoc.

Anyway, with Markdown you need and additional suffix part to make the anchor unique.
And here the date part comes into play. Even if the first part of the hash (version without dots) is non-unique, then the third part of the hash (the date) will make the difference.

Please provide a bit of feedback, if you encounter errors on the website or have ideas on how to improve the site.
