### ISSUE TITLE
create installers for PHP7

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#516]
PHP 7 was tagged today. Its not released, yet, but the builds will show up soon... 
- http://git.php.net/?p=web/php-distributions.git;a=commit;h=2ceb3db5a2fab38882e51c712a167a1b8328bea2
- http://windows.php.net/downloads/releases/

- [x] create registries & installers for `70` series (4*2)
  - [x] webinstaller
     - [x] 32
     - [x] 64
  - [x] lite
     - [x] 32
     - [x] 64
  - [x] standard
     - [x] 32
     - [x] 64
  - [x] full 
     - [x] 32
     - [x] 64

**Comment by peane** [comment]
+1

**Comment by jakoch** [comment]
:) Incoming - stay tuned!

Notes:
Because the majority of PHP extensions is definitely not ready, i have to disable a whole bunch of them. Most of them look like this: http://windows.php.net/downloads/pecl/releases/amqp/ 
Where the last 5 builds are without binaries.

**Comment by timomayer** [comment]
will we see a new release soon with php7, nginx 1.10 and so on? would be great :)
