### ISSUE TITLE
robomongo.zip not found in webinstaller

### ISSUE THREAD

**Issue by fruor** [WPN-XM/WPN-XM#530]
tried to webinstall, when reaching robomongo.zip it gives me a 404. 
Internet connection is fine, all others download OK

**Comment by jakoch** [comment]
Hey fruor, 

thank you for reporting the issue. 

The Robomongo guys run a funding campaign at their original website to keep the project alive.
They moved the download website and all downloads to a subdomain to indicate that the project might stop. The new URL is http://app.robomongo.org/download.html

I've fixed the registry links and synced it with the server. 
You are good to download again.

Merry Christmas, Jens
