### ISSUE TITLE
self-updating executable

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#536]
The Server Control Panel executable should be self-updating.

**Comment by jakoch** [comment]
Hey everyone, 

i want to share the latest development progress: the SelfUpdater finally landed. :tada: :rocket:

The Server Control Panel is now able to check, if you use the the latest available version.
If you are not up-to-date, it will automatically download the latest version and update itself.

Best, Jens

**Comment by klonos** [comment]
Yay! :fireworks: Thanx Jens!
