### ISSUE TITLE
Trojan in install files: Win32/Varpes.J!plock 

### ISSUE THREAD

**Issue by sarjey** [WPN-XM/WPN-XM#543]
Hi!

I tried to install v 0.8.6 Lite 64bit but is warned by MS antivirus that the installation contains the trojan Win32/Varpes.J!plock.

Please investigate.

-sr

**Comment by jakoch** [comment]
Could you specify:

* The file you download (link please)
 - Which installer exactly? 
 - Where did you download from? Github Releases or a third-party download site?
* When did it report this (on download, or later?)
* What were the details of the report.

-----

Here is the [VirusTotal Report](https://www.virustotal.com/de/file/17d1158cf0d398e7a58a9985eabedcc9e29a0e0db8f140e98c764a06198516ce/analysis/) for the following download: [WPNXM-0.8.6-Lite-Setup-php56-w64.exe](https://github.com/WPN-XM/WPN-XM/releases/download/v0.8.6/WPNXM-0.8.6-Lite-Setup-php56-w64.exe)

The report shows "Win32/PrcView potentially unsafe".
This is because of the included Process Killer tool (process.exe).
Its a very powerful system administration tool, which allows listing and kills of running processes.
It is often reported, but not dangerous. We use this (next to taskkill and tskill) to stop running servers.
The keyword here is **potentially**. 
It will be removed with the next release, because i'm tired of explaining.


----

Regarding: Win32/Varpes.J!plock
 - Can not reproduce, because i'm not using Windows Defender.
 - Can't find anything over at Avira and Kaspersky when searching for "Win32/Varpes.J!plock" in their AV databases.

**Comment by sarjey** [comment]
Hi!

I'm sorry if this is a false positive but I think it's relevant to get this
sorted out - I'm probably not the only one using Defender.

Downloaded from http://wpn-xm.org/

Svein Roald


Snip from defender report:

The following error occurred: Error code 0x80508023. The program could not
find the malware and other potentially unwanted software on this computer.

Category: Trojan

Description: This program is dangerous and executes commands from an
attacker.

Recommended action: Remove this software immediately.

Items:
file:C:\Users\Roald\AppData\Local\Temp\is-3FIN0.tmp\WPNXM-0.8.6-Lite-Setup-php55-w64.tmp

Get more information about this item online.

2016-02-08 12:47 GMT+01:00 Jens A. Koch <notifications@github.com>:

> Could you specify:
>
>    - The file you download (link please)
>       - Which installer exactly?
>       - Where did you download from? Github Releases or a third-party
>       download site?
>    - When did it report this (on download, or later?)
>    - What were the details of the report.
>
> ------------------------------
>
> Here is the VirusTotal Report
> <https://www.virustotal.com/de/file/17d1158cf0d398e7a58a9985eabedcc9e29a0e0db8f140e98c764a06198516ce/analysis/>
> for the following download: WPNXM-0.8.6-Lite-Setup-php56-w64.exe
> <https://github.com/WPN-XM/WPN-XM/releases/download/v0.8.6/WPNXM-0.8.6-Lite-Setup-php56-w64.exe>
>
> The report shows "Win32/PrcView potentially unsafe".
> This is because of the included Process Killer tool (process.exe).
> Its a very powerful system administration tool, which allows listing and
> kills of running processes.
> It is often reported, but not dangerous. We use this (next to taskkill and
> tskill) to stop running servers.
> The keyword here is *potentially*.
> It will be removed with the next release, because i'm tired of explaining.
> ------------------------------
>
> Regarding: Win32/Varpes.J!plock
>
>    - Can not reproduce, because i'm not using Windows Defender.
>    - Can't find anything over at Avira and Kaspersky when searching for
>    "Win32/Varpes.J!plock" in their AV databases.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPN-XM/WPN-XM/issues/543#issuecomment-181332287>.
>



-- 
Vennlig hilsen / best regards,

Svein Roald Jørgensen

**Comment by jakoch** [comment]
> I'm sorry if this is a false positive but I think it's relevant to get this
sorted out - I'm probably not the only one using Defender.

Thank you for reporting! We take security issues very seriously.

You are not the only one using Defender.
Other potential users of our software could be blocked from using it by such reports. 

I will request scans from other AV services to provide double checking and clear the situation.

**Comment by jakoch** [comment]
Response from the Microsoft Malware Protection Center:

> Thank you for your inquiry. 
 
> We examined samples you referenced in your request but **were not able to replicate detection** reported using [**latest signature definitions** available for download](https://www.microsoft.com/security/portal/definitions/adl.aspx).

> To complete our investigation, we will need full details about the event created to be sent to us, in particular we will need to collect MPSupportFiles.cab file that contains all the created log files.
 
> Please refer to this article on how to collect necessary support logs:
http://support2.microsoft.com/kb/923886
https://support.microsoft.com/en-us/kb/902093
 
> Once we receive this information we will continue our investigation.
 
> Sincerely,
Microsoft Malware Protection Center

@sarjey 
Please update your Defender signature definitions to the latest version.
In case you want to continue the investigation please provide the necessary support logs.
I will forward them to MS MPC.

**Comment by sarjey** [comment]
Hi Jens,

Thank you for looking into this. I still get the same detection warning
with the latest definition files installed.

I'm unable to send the requested log file as an mail attachment. It exceeds
your mailbox limits.

Can I send it to an other e-mail address?

-sr
​​

2016-02-09 13:51 GMT+01:00 Svein Roald Jørgensen <roald@androide.no>:

> Hi Jens,
>
> Thank you for looking into this. I still get the same detection warning
> with the latest definition files installed.
>
> Attached you will find the requested log files.
>
> Svein Roald
>
> 2016-02-09 13:07 GMT+01:00 Jens A. Koch <notifications@github.com>:
>
>> Response from the Microsoft Malware Protection Center:
>>
>> Thank you for your inquiry.
>>
>> We examined samples you referenced in your request but *were not able to
>> replicate detection* reported using *latest signature definitions*
>> available for download
>> <https://www.microsoft.com/security/portal/definitions/adl.aspx>.
>>
>> To complete our investigation, we will need full details about the event
>> created to be sent to us, in particular we will need to collect
>> MPSupportFiles.cab file that contains all the created log files.
>>
>> Please refer to this article on how to collect necessary support logs:
>> http://support2.microsoft.com/kb/923886
>> https://support.microsoft.com/en-us/kb/902093
>>
>> Once we receive this information we will continue our investigation.
>>
>> Sincerely,
>> Microsoft Malware Protection Center
>>
>> @sarjey <https://github.com/sarjey>
>> Please update your Defender signature definitions to the latest version.
>> In case you want to continue the investigation please provide the
>> necessary support logs.
>> I will forward them to MS MPC.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/WPN-XM/WPN-XM/issues/543#issuecomment-181838703>.
>>
>
>
>
> --
> Vennlig hilsen / best regards,
>
> Svein Roald Jørgensen
>
>
>


-- 
Vennlig hilsen / best regards,

Svein Roald Jørgensen

**Comment by jakoch** [comment]
I suggest to use https://www.wetransfer.com/ (or any other cloud storage, e.g. Dropbox, OneDrive, Box) and post the download link.

**Comment by sarjey** [comment]
Log file, as requested.

http://1drv.ms/1K9z0Zq

2016-02-09 14:32 GMT+01:00 Jens A. Koch <notifications@github.com>:

> I suggest to use https://www.wetransfer.com/ (or any other cloud storage,
> e.g. Dropbox, OneDrive, Box) and post the download link.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPN-XM/WPN-XM/issues/543#issuecomment-181866451>.
>



-- 
Vennlig hilsen / best regards,

Svein Roald Jørgensen

**Comment by jakoch** [comment]
Thank you. 
I've send the link to the Microsoft Malware Protection Center.

**Comment by jakoch** [comment]
Response from the Microsoft Malware Protection Center:

> Thank you for your recent inquiry about WPN-XM Server Stack.  New definition library for Microsoft Anti-Malware has been updated. We believe this new definition library contains the updates necessary to resolve your question.

> New definition library is now available for users who subscribe to the automatic definition update mechanism, as well as users who choose to manually update their definition library.

 > We encourage you to try these new definitions and ensure your inquiry has been resolved.  If your machine has not been updated with this version of definitions you can download and install the definitions manually following these steps:
 
>    Go to http://www.microsoft.com/security/portal/definitions/adl.aspx
>    Download the corresponding definitions (32 bit or 64 bit based on your operating system)
>   Run the downloaded file to install the new definitions

 > We apologize for any inconvenience this may have caused.  If you have any additional questions related to this inquiry, please contact us at mpcreply@microsoft.com.  Should you need to contact us in the future regarding a question unrelated to this inquiry, please fill out the appropriate form at http://www.microsoft.com/security/portal/mmpc/vendor/resources.aspx. 

> Thank you for contacting Microsoft. 

> Sincerely, 

> Microsoft Malware Protection Center

**Comment by sarjey** [comment]
I can confirm that the trojan warning is gone with the latest signature
files.

Great job with making WPNXM!

Regards,

Svein Roald

2016-02-11 11:28 GMT+01:00 Jens A. Koch <notifications@github.com>:

> Response from the Microsoft Malware Protection Center:
>
> Thank you for your recent inquiry about WPN-XM Server Stack. New
> definition library for Microsoft Anti-Malware has been updated. We believe
> this new definition library contains the updates necessary to resolve your
> question.
>
> New definition library is now available for users who subscribe to the
> automatic definition update mechanism, as well as users who choose to
> manually update their definition library.
>
> We encourage you to try these new definitions and ensure your inquiry has
> been resolved. If your machine has not been updated with this version of
> definitions you can download and install the definitions manually following
> these steps:
>
> Go to http://www.microsoft.com/security/portal/definitions/adl.aspx
> Download the corresponding definitions (32 bit or 64 bit based on your
> operating system)
> Run the downloaded file to install the new definitions
>
> We apologize for any inconvenience this may have caused. If you have any
> additional questions related to this inquiry, please contact us at
> mpcreply@microsoft.com. Should you need to contact us in the future
> regarding a question unrelated to this inquiry, please fill out the
> appropriate form at
> http://www.microsoft.com/security/portal/mmpc/vendor/resources.aspx.
>
> Thank you for contacting Microsoft.
>
> Sincerely,
>
> Microsoft Malware Protection Center
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPN-XM/WPN-XM/issues/543#issuecomment-182795712>.
>



-- 
Vennlig hilsen / best regards,

Svein Roald Jørgensen

**Comment by jakoch** [comment]
I'm glad we resolved this issue. 
Thank you again for reporting and working with this stack, Svein.

Best, Jens
