### ISSUE TITLE
Webinterface: "Projects" and "Tools" sections not responsive.

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#546]
This is what currently happens when the screen width gets small enough to force these two sections to wrap:

![wpn-xm-webinterface-projects_and_tools-not_wrapped_properly](https://cloud.githubusercontent.com/assets/2423362/13368902/22b82016-dd43-11e5-825e-ba799afc8328.png)

Perhaps have them take the full width of the container ```content-centered``` div?

**Comment by jakoch** [comment]
Thanks for reporting this issue.

I think its already fixed, in the [webinterface@dev](https://github.com/WPN-XM/webinterface/tree/develop) branch. All changes for the upcoming release are danling in [PullRequest19](https://github.com/WPN-XM/webinterface/pull/19).

It looks like this now, when the screen width gets small:

![project-tools-responsive](https://cloud.githubusercontent.com/assets/85608/13370111/825940b6-dcff-11e5-8abd-ea1fbf054a5a.png)

But the menu is not responsive, when the screen gets smaller then its width.. well.
Contributions welcome!
