### ISSUE TITLE
allow custom branding of installers

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#588]
##### Problem description

The installers are branded with the WPN-XM default installer images.
We have individual images per installer type: full, lite, standard, web.
##### Expected behavior

It should be possible to use custom images on the installer to brand it.
This allows to style an installer for a specific binary or PHP application.
For instance, a seperate NodeJS installer with Node logo or a Lite installer with Wordpress with Wordpress logo.
##### Possible solution
- introduce build constant `branded_installer` or `custom_installer` with the software name 
- add an innosetup installer asset folder to the submodules  `software` and `php-software`
  - `{software}\innosetup\assets`
- modify the innosetup installer to load the assets from the software folder, instead of the main asset folder
- additionally: create a placeholder asset pack for the innosetup installer
  - so that people have something to work with and can easily modify the images

**Comment by jakoch** [comment]
Lack of interest by the PHP community at large.
Why should i work for random CMS communities.

**Comment by klonos** [comment]
@jakoch just wanted to let you know that I am a long-time user of WPN-XM and I greatly appreciate your efforts in maintaining this project. Like myself, I'm sure that there are many others out there that also benefit from using WPN-XM.

I understand that each person can have very little time in their lives and that everyday life and its problems often take the best of us, but please to not let that put you off.

> Why should i work for random CMS communities and do the integration for them...

For the same reason these CMS communities (talking about open-sourced ones) work in providing the respective projects out there for the people of this earth to put to good use.

I personally have very limited time in my life and terrible personal circumstances, having to spend most of the year away ("away" as in the other side of the world) from my wife and 5yo daughter (she was only 2yo when I left my country). Despite all that, if you check my GitHub profile, you will see that I am very active, trying to contribute as much as I can in open source. This gives me great pleasure and takes my mind off of all the bad thoughts that no matter what I do keep creeping in my brain every single day.

Please keep up the good work knowing that there are people out there whose life you make easier. Then these people go on developing open-source projects that in turn help other people build communities that help this world become a better place. And you are a part of all this. Never forget that.

**Comment by jakoch** [comment]
Thank you for writing these lines, but it simply doesn't work out...
I get requests for the next version, but i can't deliver, because there are still open issues.
I can place any bounty on a ticket, but i don't get any contributions.
I've tried to find developers to join the team, but failed. 
Maintaining a stack like this needs teamwork. But for the project it's like there is nobody out there.

**Comment by jakoch** [comment]
How open-source works:

![herbert_arbeitet](https://cloud.githubusercontent.com/assets/85608/24145292/d4c65b00-0e30-11e7-84a2-49df1969fcf3.jpg)
