### ISSUE TITLE
drop PHP 5.5 installers

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#590]
PHP 5.5 faces EOL 10 Jul 2016. In 1 month.
It doesn't make sense to build and ship these installers.

- [x] remove installers  for PHP 5.5
- [x] remove next-version/unreleased installer registries for PHP 5.5
- [x] disable the listing of PHP5.5 extensions on the Components page http://wpn-xm.org/components.php
- [x] adjust cross-diff tools accordingly

**Comment by klonos** [comment]
Just something to bare in mind when deciding to remove php versions that come to an EoL: web hosting companies tent to be very slow when it comes to deploying new versions of php (or entire distros of popular linux images that include the new versions). So people are stuck with older versions for even as much as up to a couple of years or more. This happens more often with ~~cheap~~ affordable hosting companies, but that's what people use.

In Drupal and now in its fork Backdrop CMS, we try to look at market trends before dropping support for a php version. 5.5 seems to hold a good ~20% still, but what is more interesting is that 5.4 and 5.3 both have a ~30% each, with 5.2 and 5.6 having ~10% each ...and 5.7 holding a disappointing 0.1% (equal to the usage stats of 5.0). All these stats are indicative of this "slow adoption" tendency.

Point is that web devs need to be developing and testing on the versions that they are to deploy to. I think that it would be wise to still keep 5.5 around for a little while longer.

**Comment by jakoch** [comment]
Hey Gregory!

>  I think that it would be wise to still keep 5.5 around for a little while longer.

Given the amount of work i piled up for this project,
i qualify easily as an insane, but not as a wise man... :) 

But, yes, i have this on my mind. Also because we had the discussion about the slow adoption before (https://github.com/WPN-XM/WPN-XM/issues/497), when i dropped PHP54. According to http://phpversions.info/shared-hosting/ the adoption of 7 has improved, but 5.3 is really slow on its fade out (LTS). 

In regard to PHP55: 
I want to keep parity with the supported versions of PHP. 
This allows me to concentrate on 56 and 70 and reduce some work. 
I missed the chance to do a release with 55 at the time when 7 was released.
But that wasn't possible, because the SCP and the webinterface were and are not in a stable state.

From the old thread:
> Users can still "downgrade" by downloading a previous version.

**Comment by klonos** [comment]
All fair enough. I absolutely respect the time you spend on this project and it's entirely up to you. I was just thinking out-loud and had totally forgotten about the discussion for 5.4. Carry on :smile:

**Comment by jakoch** [comment]
Update.. we have new data

Jordi published new PHP stats today: https://seld.be/notes/php-versions-stats-2016-1-edition

> 5.5 is still big but less so, while 5.6 got a huge boost to become the main version. The big surprise is that we have 20% of PHP7 already! 

> 5.5 is taking the bulk of it though which makes me a bit sad :) I wish there was more love for 7

And that's also my opinion. Let's shape the adoption curve a bit ;)

**Comment by klonos** [comment]
😄
