### ISSUE TITLE
Control panel won't start if startminimized=1 and "The following processes are already running" prompt is to be shown

### ISSUE THREAD

**Issue by michaelkonecny** [WPN-XM/WPN-XM#591]
##### Problem description
I already had PostgreSQL installed before installing WPN-XM, so each time I run the WPN-XM Server Control Panel, I get the prompt "The following processes are already running: postgres ... please choose the processes you wish to shutdown".
If I activate the option "Start minimized to Tray", WPN-XM won't start (Windows says "WPN-XM Server Control Panel has stopped working" immediately after I run it).

I'm on Windows 7 Professional.
WPN-XM version 0.8.5+0a7e025

##### Expected behavior
The program shouldn't crash.

##### Possible solution
The startminimized option should be ignored in case a prompt needs to be shown.

##### Workaround for anyone stuck with this
Set startminimized to 0 in wpn-xm.ini.

**Comment by jakoch** [comment]
Thank you for reporting, Michael! 
I could reproduce it.
