### ISSUE TITLE
Code of conduct contains "[INSERT EMAIL ADDRESS]"

### ISSUE THREAD

**Issue by KJTsanaktsidis** [WPN-XM/WPN-XM#599]
"Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting a project maintainer at [INSERT EMAIL ADDRESS]". Really sends a message that you care!

Maybe it should be fixed :)

**Comment by jakoch** [comment]
Thank you for reporting. Yes, this should be fixed.

**Comment by jakoch** [comment]
I've updated the CodeOfConduct to the latest version, v1.4.0 and added my email.
