### ISSUE TITLE
WPNXM-0.8.6-LiteRC-Setup-php70-w64 Adminer

### ISSUE THREAD

**Issue by jorgeusify** [WPN-XM/WPN-XM#608]
##### Problem description
The adminer in WPNXM-0.8.6-LiteRC-Setup-php70-w64 is using the deprecated PHP 4 constructor instead of the PHP 7 constructor/ 

##### Expected behavior
No errors or warnings must show.

##### Possible solution
Please updated the adminer's php code to comply with php 7.

**Comment by jakoch** [comment]
Hello Jorge,

thank you for reporting this issue.
Our installers include an old version of Adminer, which doesn't support the new constructors.

(Long story: This was an upstream issue with Adminer, which i've immediatly fixed and reported back in June 2015! You can find my pull request here https://github.com/vrana/adminer/pull/135
My patch was ignored and a patch by dg was merged instead, see https://github.com/vrana/adminer/pull/142).

Steps:
1. please download a newer version of Adminer, e.g. https://www.adminer.org/static/download/4.2.5/adminer-4.2.5.php
2. rename downloaded file to `adminer.php`
3. go to `www\tools\adminer` and replace the `adminer.php` file
That's it.

Regards, Jens

**Comment by jorgeusify** [comment]
Thanks!
