### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by krishnaTORQUE** [WPN-XM/WPN-XM#613]
Unable to download WPN-XM 
from: http://wpn-xm.org/downloads.php
Version:  WPNXM-0.8.6-Full-Setup-php56-w64.exe
it fail everytime

**Comment by jakoch** [comment]
> Version: WPNXM-0.8.6-Full-Setup-php56-w64.exe it fail everytime
Please try the direct download link:
https://github.com/WPN-XM/WPN-XM/releases/download/v0.8.6/WPNXM-0.8.6-Full-Setup-php56-w64.exe

**Comment by krishnaTORQUE** [comment]
thank you

**Comment by jakoch** [comment]
You are welcome
