### ISSUE TITLE
High dpi support for the control panel window

### ISSUE THREAD

**Issue by Logifire** [WPN-XM/WPN-XM#618]
##### Problem description

On high dpi displays, the icons/buttons/text is tiny
##### Expected behavior

Should scale up
##### Possible solution

Don't know

![high-dpi-support-missing](https://cloud.githubusercontent.com/assets/16954276/19242657/765af9a4-8f14-11e6-8d38-691203785114.jpg)

**Comment by jakoch** [comment]
Thank you for reporting the issue.

**Comment by jakoch** [comment]
Not enough money? Increasing to **500€**.

**Comment by jakoch** [comment]
https://blogs.technet.microsoft.com/askcore/2016/08/16/display-scaling-changes-for-the-windows-10-anniversary-update/

**Comment by jakoch** [comment]
Increasing the bounty to **1000€**.

**Comment by jrose2002** [comment]
If you have updated to the anniversary edition here is a quick fix

![wpn-xm dpi scaling qf](https://user-images.githubusercontent.com/3163840/31492877-8b9e21c8-af12-11e7-910f-5054265a4d2c.png)

**Comment by Logifire** [comment]
Yep this is a useful quick fix, I don’t think @jakoch need to spend the time on this issue anymore is, it’s a bit blurry but absolutely useful :-)

**Comment by jakoch** [comment]
- Let's try the new Qt attributes for High-Dpi support. We are switching from Qt::AA_Use96Dpi to Qt::AA_UseHighDpiPixmaps and Qt::AA_EnableHighDpiScaling.
- removing the bounty
