### ISSUE TITLE
[looking for developers to join the team] <------------------------------------

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#625]
Hello WPN-XM Community!

I'm looking for someone to join the team, to assist me with further developing WPN-XM.
The system is build using InnoSetup, PHP, C++/Qt, AsciiDoc.

I need support in the following areas:

**Server Control Panel**
The focus of the development is on the Server Control Panel, which is written in C++ using Qt.
You need to have experience with C++/Qt, and also affinity for using web technologies on Windows.

**Installers**
The focus of the development is on the InnoSetup based installers.
You need to have experience with InnoSetup.

**Updater & Registries**
The maintenance of the software registry, including metadata, configs and tasks for the stack components and PHP applications. 
You need to have experience with PHP. 

**Testing**
The focus of the development is on software testing.
You need to have experience with PHP and PHPUnit.

**Documentation**
The focus of your work is the documentation of our software components and installed software components, including basic configuration and setup details.
You need to have experience with AsciiDoc.

**Webinterface**
The focus of the development is on the webinterface.
You need to have experience with PHP and PHPUnit.

----

**Important**
- Please provide a _proven track record of open-source contributions_ to PHP or C++/Qt projects.
- You should be _fluent_ in english or german language.
- Please state _how many hours per week_ you would be available, and at what _hourly rate_.

Thank you, Jens

**Comment by lovebdsobuj** [comment]
I will try 
- **Installers / Updater&Registry**
- **Testing**
