### ISSUE TITLE
Hosts Manager crash

### ISSUE THREAD

**Issue by tobiasfichtner** [WPN-XM/WPN-XM#626]
##### Problem description
if u try to open the Hosts Manager oder Tray-Icon the SCP crashs

**Comment by jakoch** [comment]
Which version of the SCP?

**Comment by tobiasfichtner** [comment]
SCP 0.8.6., latest from web-installer.

**Comment by jakoch** [comment]
Sorry, i can't reproduce this issue. 
I used `wpnxm-scp-0.8.6-x86_64_boxed.zip` on Win10 for testing. 

**Could you provide additional steps, which help in reproducing the issue?**

![crash](https://cloud.githubusercontent.com/assets/85608/20263835/b1b3d8e4-aa68-11e6-9936-40853dd95e60.png)

**Comment by jakoch** [comment]
**Could you provide additional steps, which help in reproducing the issue?**

**Comment by jakoch** [comment]
No response..  Houston, we have a communication problem. 
Closing.
