### ISSUE TITLE
404 phpmemcacheadmin.zip

### ISSUE THREAD

**Issue by RHITNL** [WPN-XM/WPN-XM#627]
##### Problem description
While using the 0.8.6 webinstaller on Windows 10, I get a 404 error on phpmemcachedadmin.zip
![image](https://cloud.githubusercontent.com/assets/6173448/20859154/ea4018e2-b956-11e6-9dc0-ddb7a7df7188.png)

##### Expected behavior
it should give a http 200 of course :) 

##### Possible solution
Could you please make sure the file is in place or the correct download location is used in the executer?
Thanks!

**Comment by RHITNL** [comment]
Looks like a different redirect URL
File is now available at different location.
Old: http://phpmemcacheadmin.googlecode.com/files/phpMemcachedAdmin-1.2.2-r262.zip
New: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/phpmemcacheadmin/phpMemcachedAdmin-1.2.2-r262.zip

**Comment by jakoch** [comment]
Hey Ralph!
This is probably because of the googlecode shutdown.
Thank you for reporting the issue and finding the new location, which saves me some time!
Registry update incoming...

**Comment by RHITNL** [comment]
You are welcome Jakoch. Just posted another 404 error. Thank you for providing this nice prorject 👍
