### ISSUE TITLE
Default credentials for PostgreSQL

### ISSUE THREAD

**Issue by josephgodwinkimani** [WPN-XM/WPN-XM#638]
##### Problem description
I cannot log into PostgreSQL through adminer. The error stipulates that no such role exists - _Unable to connect to PostgreSQL server: FATAL: role "root" does not exist_

##### Expected behavior
Login with username: _root_ with a blank as my password

##### I have tried:

1. pgAdminIII, it cannot connect to WPN-XM PostgreSQL server for me to create roles to solve the issue.
2. Editing the pgpsss.conf in ../AppData/postgresql according to these [specifications](https://www.postgresql.org/docs/9.4/static/libpq-pgpass.html) to solve the issue.
3. Using psql in WPN-XM installation
 ```
C:\WPN-XM\bin\pgsql\bin>psql -U postgres
psql: FATAL:  role "postgres" does not exist
```

##### Possible solution
Proper user documentation. [This](http://wpn-xm.github.io/docs/user-manual/en/#_postgresql) is not enough.

**Comment by jakoch** [comment]
Hello Joseph!

Please run `pgsql -l` first, which lists the created databases including owners.
There should be a database `postgres`.
The username should be the user you ran the installer with.

Alternatively, you can also find out the default username by running `pgsql --help`.
The name is displayed at the end of the line containg `-U, --username=NAME` with `"default: username"`.

We do a very minimal setup for PostgreSQL from the installer:
1. it fetches the zip and extracts it into `/bin/pgsql`
2. then it runs `initdb.exe --encoding=UTF-8 --pgdata=..\data` to create an initial database
Then, from the Server Control Panel the following command is used:
3. for starting: `pg_ctl -D ..\data -l logfile.txt start`

**Comment by jakoch** [comment]
Are you ok with the changes? Please give me a feedback. 
Do you have any other ideas for things i need to change?

**Comment by jakoch** [comment]
...

**Comment by josephgodwinkimani** [comment]
Thank you for the support. I found a workaround where I used my computer account's name as the username and a blank password. _root_ username will not work. in reference to @jakoch [commit](https://github.com/WPN-XM/docs/commit/96e6ac5cd2197d8a789a7c4c5fc14c2c4292ab0a):  _yourdb_ option is not necessary in my opinion
