### ISSUE TITLE
version switch not working

### ISSUE THREAD

**Issue by fox1406** [WPN-XM/WPN-XM#644]
#### What's the problem?
When you try to switch the version in webpanel, its not working since you're trying to rename a folder from which the `php-cgi.exe` is currently running from. 

#### What do we need to reproduce the issue?
PHP directories  structure in my `bin` folder:
- php
- php-5.6.30
- php-7.1.3

#### More details
Screenshot of error: http://image.prntscr.com/image/652e6ac97168460ea531a5c7e8a13423.png
PHP error log: `[22-Mar-2017 02:37:31 Europe/Berlin] PHP Warning:  rename(E:\wpnxm\bin\php,E:\wpnxm\bin\php-7.0.17): The process cannot access the file because it is being used by another process. (code: 32) in E:\wpnxm\www\tools\webinterface\php\Helper\PHPVersionSwitch.php on line 39`

**Comment by jakoch** [comment]
Thank you for reporting the issue.
I can reproduce it.
I wasn't expecting that someone tries to change the PHP, while it is running. 
But we should protect the user in this case, too.

- https://github.com/WPN-XM/webinterface/blob/9e215098a81cce0d647d9f58fc19cc71682cf039/php/Controller/config.php#L224
  - To stop the running PHP, the function needs a call to `Webinterface\Helper\Daemon::stopDaemon('php');` as the first step.

**Comment by jakoch** [comment]
And when i look at the code, it should actually be "stop only if running" + "restart only if was running":

- if isRunning(PHP) then PHPwasRunning=true + stop PHP
- if PHPwasRunning running then restart PHP

We need `isRunning('PHP')`. 
But.. the new version of the stack uses the `php-cgi-spawner.exe` to spawn `php-cgi.exe`.
That means i have to alter the process detection and implement the same code i already have in the SCP, to check for both processes and the process tree. Crap. This gets really complicated.

**Comment by jakoch** [comment]
Status: 
- won't fix for the webinterface.
- added PHP Version switching to the SCP (PHP - Configuration - Version Switch)
