### ISSUE TITLE
php7 version doesn't work because php5 is missing...

### ISSUE THREAD

**Issue by atiredmachine** [WPN-XM/WPN-XM#645]
#### What's the problem?
nginx won't start..  Gives this error:  php-cgi.exe System Error The program can't start because php5.dll is missing from your computer.

#### What do we need to reproduce the issue?

Windows 8.1
This is the file I downloaded: WPNXM-0.8.5-LiteRC-Setup-php70-w64.exe

| Q                                        | A
| -----------------------------------------| ---------------
| WPN-XM Version (`wpn-xm.exe --version`)  | x.y.z
| Windows Version (`ver`)                  | x.y.z

#### How to reproduce the issue?
Please add steps to reproduce the issue.

1. 
2.
3.

#### What should have happened?
Please describe the expected behavior.

#### Do you have an idea for a solution?
Please describe a possible solution.

**Comment by jakoch** [comment]
Hey Thor!

I've downloaded and installed `WPNXM-0.8.5-LiteRC-Setup-php70-w64.exe`.
I can not reproduce the error. It works for me out of the box.

Also any PHP7 version includes php7.dll and not php5.dll. 
I'm not sure what's going on there.

Would you be so nice to add more steps to reproduce the issue? Thank you.

Yours, Jens

**Comment by jakoch** [comment]
Sorry, i just noticed that i tested the latest version 0.8.6.

 `WPNXM-0.8.5-LiteRC-Setup-php70-w64.exe`:

Has several problems, which were adressed in the `0.8.6` version.

- nginx was not extracted into `bin\nginx`, instead you get a versionized folder `bin\nginx-1.9.2`
  - workaround is to move all files from  `bin\nginx-1.9.2` into `bin\nginx`
- The PHP extension xdebug wasn't compatible with PHP7 version at that time. You need to download a matching version and replace `php_xdebug.dll`.
```
D:\wpnxm-085-literc70-64\bin\php>php -v
Failed loading d:\wpnxm-085-literc70-64\bin\php\ext\php_xdebug.dll
PHP 7.0.0beta1 (cli) (built: Jul 10 2015 10:56:50)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```
just remove the inclusion of xdebug. You find it at the bottom of `php.ini`.
