### ISSUE TITLE
No Uninstall...

### ISSUE THREAD

**Issue by atiredmachine** [WPN-XM/WPN-XM#646]
#### What's the problem?
There is no uninstall executable included.  There is a shortcut called "Uninstall WPN-XM Server Stack" that simply links to "This PC"...

#### What do we need to reproduce the issue?
This is the file I downloaded: WPNXM-0.8.5-LiteRC-Setup-php70-w64

**Comment by jakoch** [comment]
Installed `WPNXM-0.8.5-LiteRC-Setup-php70-w64` into `D:\wpnxm-085-literc70-64`. 

Check, if file exists `D:\wpnxm-085-literc70-64\unins000.exe`:

![clipboard01](https://cloud.githubusercontent.com/assets/85608/24415459/da214d6a-13e1-11e7-8df2-5321f98b6841.png)

Check, if "Uninstall" shortcut points to the `unins000.exe` executable:

![clipboard02](https://cloud.githubusercontent.com/assets/85608/24415538/0d1b086e-13e2-11e7-811d-3047f441ff0e.png)

@atiredmachine ?

**Comment by jakoch** [comment]
And, of course, the workaround is to manually delete the folder.
