### ISSUE TITLE
cannot connect through Localhost

### ISSUE THREAD

**Issue by Rockapella** [WPN-XM/WPN-XM#648]
#### What's the problem?
I have WPN-XM installed on my Windows 10 machine and can navigate to the admin page by typing in my public ip address, private ip address, or domain. I cannot connect to the site though localhost for some reason. There are no logs that I can see which would tell me something is wrong.

#### What do we need to reproduce the issue?
Please tell us details about your environment, including software versions.

| Q                                        | A
| -----------------------------------------| ---------------
| WPN-XM Version (`wpn-xm.exe --version`)  | 0.8.6
| Windows Version (`ver`)                  | 10

#### How to reproduce the issue?
Please add steps to reproduce the issue.

1. Go to Chrome/IE/Firefox
2. Type in Localhost in the address bar

#### What should have happened?
Should have brought me to localhost/tools/webinterface/, but instead says "localhost refused to connect"

#### Do you have an idea for a solution?
I believe there may be an issue within my configuration. It seems strange that it works when using the domain, public IP, or private IP and not work with localhost.

**Comment by Rockapella** [comment]
I restarted my server and now I can navigate to localhost and it works.

**Comment by jakoch** [comment]
Glad you could solve it. Please let me know, if you run into other issues. Thanks, Jens
