### ISSUE TITLE
Avast reports IDP.Generic Malware on PostgreSQL (Win 7)

### ISSUE THREAD

**Issue by markusfeix** [WPN-XM/WPN-XM#658]
#### What's the problem?
Hello,
I just downloaded and installed "WPNXM-0.8.6-Full-Setup-php56-w64" on Windows 7.
When starting all daemons my virus scanner (Avast) hits alarm on "IDP.Generic" detected due to behaviour of PostgreSQL.

Please describe the issue you are running into or raise a question.

#### What do we need to reproduce the issue?
See above.

| Q                                        | A
| -----------------------------------------| ---------------
| WPN-XM Version (`wpn-xm.exe | "WPNXM-0.8.6-Full-Setup-php56-w64"
| Windows Version 7 | 7

#### How to reproduce the issue?
Please add steps to reproduce the issue.

1. See above.
2.
3.

#### What should have happened?
PostgreSQL not triggering the malware alarm.

#### Do you have an idea for a solution?
Provide PostgreSQL without that behaviour.

**Comment by jakoch** [comment]
Hey!
Thank you for the report. It's a false positive. 
They should update their signatures.
