### ISSUE TITLE
mongoDB could not start

### ISSUE THREAD

**Issue by 8768454982** [WPN-XM/WPN-XM#659]
#### What's the problem?
Please describe the issue you are running into or raise a question.

#### What do we need to reproduce the issue?
Please tell us details about your environment, including software versions.

| Q                                        | A
| -----------------------------------------| ---------------
| WPN-XM Version (`wpn-xm.exe --version`)  | x.y.z
| Windows Version (`ver`)                  | x.y.z

#### How to reproduce the issue?
Please add steps to reproduce the issue.

1. 
2.
3.

#### What should have happened?
Please describe the expected behavior.

#### Do you have an idea for a solution?
Please describe a possible solution.

**Comment by jakoch** [comment]
Hey! Thank you for reporting this bug.
You posted in the other ticket, that you are using WPN-XM Version 0.8.4.
Please give the latest version of WPN-XM Server Control Panel v0.8.6 a try:
https://github.com/WPN-XM/server-control-panel/releases/download/v0.8.6/wpnxm-scp-0.8.6-x86_boxed.zip

In case you need x64 you find it on the releases page: https://github.com/WPN-XM/server-control-panel/releases

Hope this fixes the MongoDB startup issue. 
Regards, Jens

**Comment by jakoch** [comment]
Fixed in the development version.
