### ISSUE TITLE
mongoBD could not start

### ISSUE THREAD

**Issue by 8768454982** [WPN-XM/WPN-XM#660]
#### What's the problem?
Please describe the issue you are running into or raise a question.

#### What do we need to reproduce the issue?
Please tell us details about your environment, including software versions.

| Q                                        | A
| -----------------------------------------| ---------------
| WPN-XM Version (`wpn-xm.exe --v0.8.4`)  | x.y.z
| Windows Version (`7`)                  | x.y.z

#### How to reproduce the issue?
Please add steps to reproduce the issue.

1. mongoBD could not start
2.
3.

#### What should have happened?
Please describe the expected behavior.

#### Do you have an idea for a solution?
Please describe a possible solution.

**Comment by jakoch** [comment]
Closing, because dupliate of #659
