### ISSUE TITLE
Wpn-XM Software Not RUN

### ISSUE THREAD

**Issue by masud5282** [WPN-XM/WPN-XM#663]
Dear WPN-XM Teams,

Please help me.
###WPNXM-0.8.6-Standard-Setup-php56-w64 Installation successful but not RUN the software.

Software Run time this a message show.... 
**This application failed to start because it could not find or load the Qt platform plugin "windows".**

**Reinstalling the application may fix this problem.**

**Comment by jakoch** [comment]
Please use a newer/development version of the SCP: https://ci.appveyor.com/api/buildjobs/j1rqhied3mt9jba6/artifacts/wpnxm-scp-dev-bcd5505-x64-msvc2017-boxed.zip

**Comment by jianbosu** [comment]
can run，but crash when i click configration butten

**Comment by tobiasfichtner** [comment]
<Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:e88ac375-c01e-00d7-4023-2af0c3000000
Time:2019-06-24T00:26:57.0655315Z</Message></Error>

**Comment by tobiasfichtner** [comment]
<Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.


> 
> 
> Please use a newer/development version of the Server Control Panel.
> 
> [wpnxm-scp-dev-bcd5505-x64-msvc2017-boxed.zip](https://ci.appveyor.com/api/buildjobs/j1rqhied3mt9jba6/artifacts/wpnxm-scp-dev-bcd5505-x64-msvc2017-boxed.zip)

**Comment by tobiasfichtner** [comment]
possible workaround is to use the previous version 0.8.5 (https://github.com/WPN-XM/server-control-panel/releases)
