### ISSUE TITLE
Download-Links Webinstalller PHP5.6 broken

### ISSUE THREAD

**Issue by tobiasfichtner** [WPN-XM/WPN-XM#664]
Download-Links Web-Installer PHP5.6 broken

both links broken, Response 404
https://github.com/WPN-XM/WPN-XM/releases/download/v0.8.6/WPNXM-0.8.6-Webinstaller-Setup-php56-w64.exe
https://github.com/WPN-XM/WPN-XM/releases/download/v0.8.6/WPNXM-0.8.6-Webinstaller-Setup-php56-w32.exe

**Comment by jakoch** [comment]
Danke! Ich hab die beiden Links rausgenommen.
