### ISSUE TITLE
Can't installl node.js package

### ISSUE THREAD

**Issue by lorz** [WPN-XM/WPN-XM#667]
#### What's the problem?
Launch 'npm install' just gives an error by console

#### What do we need to reproduce the issue?
Download WPN-XM wizard install 0.8.7 Full setup x32 version and run it on Windows 10 Workstation x64.

| Q                                        | A
| -----------------------------------------| ---------------
| WPN-XM Version (`wpn-xm.exe --version`)  | 0.8.7
| Windows Version (`ver`)                  | Windows 10 Workstation (Windows_NT 6.3.9600) x64

#### How to reproduce the issue?
Please add steps to reproduce the issue.

1. Go to .\bin\node\
2. Exec npm install <package>
3. See error log on screen

Error log:

C:\server\bin\node>npm isntall
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open 'C:\server\bin\node\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Windows_NT 6.3.9600
npm ERR! command "C:\\server\\bin\\node\\\\node.exe" "C:\\server\\bin\\node\\node_modules\\npm\\bin\\npm-cli.js" "isntall"
npm ERR! cwd C:\server\bin\node
npm ERR! node -v v0.12.7
npm ERR! npm -v 1.4.12
npm ERR! path C:\server\bin\node\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\server\bin\node\npm-debug.log
npm ERR! not ok code 0

#### What should have happened?
Package should be installed

#### Do you have an idea for a solution?
No idea.

**Comment by jakoch** [comment]
Hello Lorz!

The error message indicates that the npm expects a `package.json` file.
You are trying to run `npm` directly in the node binary folder and not in a node project folder.

Steps to avoid this issue:
Please create a new node project folder: `server\www\nodeproject`.
Then `cd` into that folder and run `...\..\bin\node\npm isntall` on the CLI.
Or if you want to create a `package.json` file run ``...\..\bin\node\npm init`.
You can also add `server\bin\node`to your PATH environment variable to make calling node/npm easier.
Referencing: https://docs.npmjs.com/creating-a-package-json-file

Btw. Both Node/npm are heavily outdated in the v0.8.7 version (v0.12.7/14.1.12). Please update manually.
1. mkdir "/server/bin/node"
2. download node - http://wpn-xm.org/get.php?s=node-x64
3. move executable into "/server/bin/node" folder
4. download npm - https://wpn-xm.org/get.php?s=nodenpm
5. extract content of npm*.zip into "/server/bin/node" folder

Please give me feedback, if this works for you and solves the issue.
Regards, Jens

**Comment by lorz** [comment]
My mistake.
